import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import vm from "node:vm";
import test from "node:test";
import { shellDom } from "../helpers/shell-dom.mjs";
const shell = await readFile(new URL("../../assets/site-shell.js", import.meta.url), "utf8");
const nav = await readFile(new URL("../../assets/site-nav.js", import.meta.url), "utf8");
function fixture() {
  const dom = shellDom(`<header class="site-header"><button id="hamburger" data-nav-toggle aria-controls="navigation" aria-expanded="false"></button><nav id="navigation"><button id="more" data-shell-menu="navigation" aria-controls="actions" aria-expanded="false">More</button><div id="actions" hidden><button id="route" data-workspace-open data-shell-focus="alert" data-shell-mirror="alert">Create alert</button><a id="link" href="./faculty_interests.html">Update researcher profile</a></div></nav><button id="workspace" data-workspace-open>Workspace</button></header><main id="results"><button id="card" data-card-more="one" data-shell-menu="card" aria-controls="site-action-list">More</button></main><dialog id="personal-workspace" data-shell-drawer><button id="close" data-workspace-close data-shell-initial-focus>Close</button><button id="alert" disabled>Alert</button></dialog><p id="status" data-shell-status="personal-workspace"></p><button id="outside">Outside</button>`);
  vm.createContext(dom.context);
  vm.runInContext(shell, dom.context);
  vm.runInContext(nav, dom.context);
  dom.get = id => dom.document.getElementById(id);
  dom.click = id => dom.dispatch("click", dom.get(id));
  dom.esc = () => dom.dispatch("keydown", dom.document.activeElement, { key: "Escape" });
  return dom;
}
test("nested mobile disclosure, Escape, outside click, Tab exit and terminal navigation have one owner", () => {
  const dom = fixture();
  dom.click("hamburger"); dom.click("more");
  assert.equal(dom.get("hamburger").getAttribute("aria-expanded"), "true");
  assert.equal(dom.get("more").getAttribute("aria-expanded"), "true");
  assert.equal(dom.document.activeElement.id, "link", "disabled canonical alert is mirrored");
  assert.equal(dom.esc().prevented, true);
  assert.equal(dom.document.activeElement.id, "more");
  assert.equal(dom.get("hamburger").getAttribute("aria-expanded"), "true");
  dom.click("more"); dom.dispatch("pointerdown", dom.get("outside"));
  assert.equal(dom.get("actions").hidden, true);
  assert.equal(dom.document.activeElement.id, "more");
  dom.click("more"); dom.get("outside").focus();
  assert.equal(dom.get("actions").hidden, true);
  assert.equal(dom.document.activeElement.id, "outside", "ordinary Tab departure is not trapped");
  dom.click("hamburger"); dom.click("more"); dom.click("link");
  assert.equal(dom.get("hamburger").getAttribute("aria-expanded"), "false");
  const count = [...dom.listeners.values()].reduce((n, entries) => n + entries.length, 0);
  vm.runInContext(shell, dom.context);
  assert.equal([...dom.listeners.values()].reduce((n, entries) => n + entries.length, 0), count);
});
test("drawer alert route mirrors availability and returns to exact results opener, without another submission", () => {
  const dom = fixture();
  dom.get("alert").disabled = false;
  dom.click("more");
  assert.equal(dom.get("route").disabled, false);
  dom.click("route");
  assert.equal(dom.get("personal-workspace").open, true);
  assert.equal(dom.document.activeElement.id, "alert");
  assert.equal(dom.get("alert").scrolled, true);
  assert.equal(dom.get("personal-workspace").contains(dom.get("status")), true);
  dom.click("close");
  assert.equal(dom.document.activeElement.id, "more");
  assert.equal(dom.get("personal-workspace").contains(dom.get("status")), false);
  dom.click("workspace");
  assert.equal(dom.document.activeElement.id, "close");
  // Native Escape dispatches close; the controller owns cleanup/restoration.
  dom.get("personal-workspace").close();
  assert.equal(dom.document.activeElement.id, "workspace");
  dom.click("workspace");
  dom.dispatch("click", dom.get("personal-workspace"), { clientX: 300, clientY: 300 });
  assert.equal(dom.get("personal-workspace").open, false);
});
test("single card menu delegates original data, fits at 320px, and cleans up after action/rerender", async () => {
  const dom = fixture();
  dom.context.SiteShell.registerMenu("card", () => [{ label: "Track", html: '<button id="watch" data-watch-opportunity="one">Alert</button>' }]);
  dom.get("card").rect = { left: 280, right: 310, top: 445, bottom: 475, width: 30, height: 30 };
  dom.click("card");
  const menu = dom.get("site-action-list");
  assert.equal(dom.document.activeElement.id, "watch");
  assert.equal(dom.get("results").contains(menu), true);
  assert.ok(parseFloat(menu.style.left) >= 8);
  assert.ok(parseFloat(menu.style.left) + 280 <= 312);
  assert.ok(parseFloat(menu.style.top) + 200 <= 472);
  dom.click("watch");
  assert.equal(dom.context.SiteShell.actionOpener(dom.get("watch")), dom.get("card"));
  assert.equal(dom.document.activeElement.id, "card");
  assert.equal(dom.get("watch").getAttribute("data-watch-opportunity"), "one", "existing delegates retain their event target through propagation");
  await Promise.resolve();
  assert.equal(dom.get("results").contains(dom.get("watch")), true, "microtask checkpoints between native capture/bubble listeners cannot detach the action");
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(dom.get("watch"), null);
  dom.click("card"); dom.dispatch("funding-finder:before-results-render", dom.document.body);
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(menu.hidden, true);
  assert.equal(dom.get("results").contains(menu), false);
  dom.click("card"); dom.get("card").remove(); dom.mutate();
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(menu.hidden, true);
  assert.equal(menu.querySelectorAll("button").length, 0);
});
