from __future__ import annotations

import copy
import gzip
import hashlib
import json
from pathlib import Path
import unittest

from scripts.import_opportunity_team_model import (
    MAX_BROWSER_BYTES,
    _canonical_bytes,
    browser_projection,
)


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config" / "opportunity_team_model.json"
BROWSER_PATH = ROOT / "data" / "opportunity_teams.js"
GENERATION_MARKER = 'meta name="opportunity-team-generation" content="{generation}"'


class OpportunityTeamModelTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
        cls.browser_bytes = BROWSER_PATH.read_bytes()

    def test_generation_is_content_derived_and_browser_projection_is_exact(self):
        payload = copy.deepcopy(self.config)
        generation = payload.pop("generation_id")
        self.assertEqual(hashlib.sha256(_canonical_bytes(payload)).hexdigest(), generation)
        expected = (
            "/* Generated by scripts/import_opportunity_team_model.py. Do not edit. */\n"
            "globalThis.OPPORTUNITY_TEAM_DATA="
            + _canonical_bytes(browser_projection(self.config)).decode("utf-8")
            + ";\n"
        ).encode("utf-8")
        self.assertEqual(self.browser_bytes, expected)

    def test_roster_and_pool_contracts_are_explicit(self):
        self.assertEqual(self.config["source_roster_counts"], {
            "total": 156,
            "rankable": 145,
            "unrankable": 11,
        })
        self.assertEqual(self.config["pool_counts"], {
            "main": 118,
            "standby": 35,
            "unadmitted": 3,
        })
        self.assertEqual(len(self.config["faculty"]), 156)
        states = {state: 0 for state in ("main", "standby", "unadmitted")}
        for profile in self.config["faculty"]:
            states[profile["pool_state"]] += 1
            self.assertTrue(profile["source_urls"])
            self.assertRegex(profile["source_checked_date"], r"^\d{4}-\d{2}-\d{2}$")
            if profile["pool_state"] == "main":
                self.assertGreaterEqual(len(profile["terms"]), 2)
            if profile["pool_state"] == "standby":
                self.assertEqual(len(profile["terms"]), 1)
        self.assertEqual(states, self.config["pool_counts"])

    def test_ten_specific_scopes_preserve_explanations_and_honest_gaps(self):
        opportunities = self.config["opportunities"]
        self.assertEqual(len(opportunities), 10)
        states = {"pass": 0, "conditional": 0, "fail": 0}
        allowed_types = {"specific_parent", "publishable_child", "declared_branch"}
        for opportunity in opportunities:
            states[opportunity["gate_state"]] += 1
            self.assertIn(opportunity["record_type"], allowed_types)
            self.assertNotIn("broad", opportunity["record_type"])
            self.assertIn(len(opportunity["members"]), {3, 4})
            self.assertEqual(len(opportunity["roles"]), 4)
            self.assertTrue(opportunity["why_team"])
            self.assertTrue(opportunity["source_url"].startswith("http"))
            for member in opportunity["members"]:
                self.assertTrue(member["why_person"])
                self.assertTrue(member["evidence_phrase"])
                self.assertTrue(member["source_url"].startswith("http"))
            for role in opportunity["roles"]:
                self.assertIn(role["coverage"], {
                    "direct", "method_transfer", "adjacent", "direct_and_adjacent", "gap",
                })
                self.assertTrue(role["rationale"])
                self.assertTrue(role["source_url"].startswith("http"))
                self.assertTrue(set(role["candidate_ids"]).isdisjoint(role["alternative_ids"]))
        self.assertEqual(states, {"pass": 2, "conditional": 7, "fail": 1})
        self.assertEqual(
            sum(opportunity["record_type"] == "publishable_child" for opportunity in opportunities),
            3,
        )
        self.assertTrue(any(opportunity["missing_skills"] for opportunity in opportunities))

    def test_html_and_runtime_references_share_the_generated_identity(self):
        generation = self.config["generation_id"]
        for name in ("match_explorer.html", "team_match.html"):
            source = (ROOT / name).read_text(encoding="utf-8")
            self.assertIn(GENERATION_MARKER.format(generation=generation), source)
            self.assertIn(f"assets/opportunity-team.js?v={generation}", source)
            self.assertNotIn("hajim-pr1", source)
        page = (ROOT / "match_explorer.html").read_text(encoding="utf-8")
        for path in (
            "assets/app.css",
            "assets/app.js",
            "assets/search-retrieval.js",
            "assets/opportunity-team-panel.js",
        ):
            self.assertIn(f'{path}?v={generation}', page)

    def test_browser_projection_stays_compact(self):
        self.assertLessEqual(len(self.browser_bytes), MAX_BROWSER_BYTES)
        self.assertLessEqual(len(gzip.compress(self.browser_bytes, compresslevel=9)), 32_000)

    def test_import_provenance_and_curated_cheme_descriptors_are_preserved(self):
        hashes = self.config["source_hashes"]
        self.assertEqual(
            hashes["faculty_workbook"],
            "4cc24fad355c5716a462b93e1f60d0c7d55d9368d7cfede330ff41daa36af130",
        )
        for key in ("faculty_model", "team_gate_model", "benchmark_lock", "faculty_expansion_lock", "team_gate_lock"):
            self.assertRegex(hashes[key], r"^[a-f0-9]{64}$")
        curated = (ROOT / "data" / "faculty_matches.js").read_text(encoding="utf-8")
        self.assertIn("heterogeneous thermal catalysis", curated)
        self.assertIn("electrocatalytic aqueous PFAS defluorination", curated)
        self.assertIn("solid-state battery electrolytes", curated)


if __name__ == "__main__":
    unittest.main()
