"""The hermetic gate must not depend on which UTC day it runs on (debt D7).

`scripts/build_changes.py` seeds each event id with `changed_at[:10]`, and
`changed_at` comes from the *current* catalog's `generated_at` -- a wall-clock
stamp that `--as-of` does not reach. Production is right to do that: a new day
should mint a new event id. The hermetic build (§8.4) is what must not vary, so
`tools/hermetic_build.sh` hands `build_changes` a `.work/` copy of the catalog
with `generated_at` pinned, via `tools/pin_generated_at.py`.

These tests prove the rollover is closed at the input rather than papered over
downstream: `tools/fingerprint.py` deliberately does **not** normalize event ids,
because an id is an opaque hash and normalizing hashes would blind the gate to
real content changes.
"""

from datetime import date
import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

from scripts.build_changes import _event_id, write_change_feed


ROOT = Path(__file__).resolve().parents[1]
AS_OF = date(2026, 8, 20)

# Two stamps either side of a midnight UTC boundary. Identical builds run minutes
# apart across that boundary are what turned the gate red.
BEFORE_MIDNIGHT = "2026-08-17T23:59:12.480321Z"
AFTER_MIDNIGHT = "2026-08-18T00:01:07.115908Z"


def _load_tool(name):
    """Import a `tools/` script by path -- `tools/` is not a package."""
    path = ROOT / "tools" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(f"_tool_{name}", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


pin_generated_at = _load_tool("pin_generated_at")
fingerprint = _load_tool("fingerprint")


def catalog_text(generated_at, records):
    """A catalog in the shape `build_catalog` writes and `load_catalog` reads."""
    payload = {
        "schema_version": 3,
        "generated_at": generated_at,
        "record_count": len(records),
        "opportunities": records,
        # The three suffixed stamps the pin must leave alone.
        "detail_enrichment_generated_at": generated_at,
        "document_evidence_generated_at": generated_at,
        "link_health_generated_at": generated_at,
    }
    return (
        "/* Generated by scripts/build_catalog.py. Do not edit by hand. */\n"
        "globalThis.GRANT_CATALOG=" + json.dumps(payload) + ";\n"
    )


def record(ident):
    return {
        "opportunity_id": ident,
        "opportunity_number": f"HERM-{ident}",
        "title": f"Hermetic opportunity {ident}",
        "agency": "Test Agency",
        "source": "Grants.gov",
        "status": "posted",
        "posted_date": "2026-08-01",
        "close_date": "2026-12-31",
        "last_updated": "2026-08-01",
        "detail_page": f"https://www.grants.gov/x/{ident}",
    }


RECORDS = [record("A1"), record("A2"), record("A3")]


def build_feed(generated_at, *, pin_to=None):
    """Run the change feed the way the hermetic build does, returning artifacts.

    With `pin_to` set, the current catalog is routed through
    `tools/pin_generated_at.py` first -- exactly what step 6 of
    `tools/hermetic_build.sh` does.
    """
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        current = work / "opportunities.js"
        current.write_text(catalog_text(generated_at, RECORDS), encoding="utf-8")
        previous = work / "opportunities.previous.js"
        previous.write_text(catalog_text(generated_at, []), encoding="utf-8")

        if pin_to is not None:
            pinned = work / "opportunities.pinned.js"
            exit_code = pin_generated_at.main(
                [str(current), str(pinned), pin_to]
            )
            assert exit_code == 0, exit_code
            current = pinned

        from scripts.build_feeds import load_catalog

        out = work / "feeds"
        summary = write_change_feed(
            load_catalog(previous), load_catalog(current), out, as_of=AS_OF
        )
        return {
            "summary": summary,
            "changes.json": (out / "changes.json").read_bytes(),
            "changes.xml": (out / "changes.xml").read_bytes(),
        }


class EventIdRolloverTests(unittest.TestCase):
    """The mechanism, pinned so a later reader does not have to rediscover it."""

    def test_an_event_id_changes_when_the_utc_date_changes(self):
        seed = ("new", record("A1"), "", "First appeared in the public catalog")
        before = _event_id(seed[0], seed[1], BEFORE_MIDNIGHT, seed[3])
        after = _event_id(seed[0], seed[1], AFTER_MIDNIGHT, seed[3])
        self.assertNotEqual(before, after)

    def test_an_event_id_is_stable_within_a_utc_day(self):
        same_day = "2026-08-17T04:02:59Z"
        self.assertEqual(
            _event_id("new", record("A1"), BEFORE_MIDNIGHT, "detail"),
            _event_id("new", record("A1"), same_day, "detail"),
        )

    def test_the_unpinned_feed_is_what_turned_the_gate_red(self):
        """Without the pin, the same build on two days differs. The defect."""
        before = build_feed(BEFORE_MIDNIGHT)
        after = build_feed(AFTER_MIDNIGHT)
        self.assertGreater(before["summary"]["new_event_count"], 0)
        self.assertNotEqual(
            fingerprint.normalize(before["changes.json"]),
            fingerprint.normalize(after["changes.json"]),
        )


class PinnedFeedIsDateIndependentTests(unittest.TestCase):
    """The fix: identical change-feed output across a simulated UTC rollover."""

    PIN = "2026-08-17T00:00:00Z"

    def test_the_change_feed_is_identical_across_a_date_rollover(self):
        before = build_feed(BEFORE_MIDNIGHT, pin_to=self.PIN)
        after = build_feed(AFTER_MIDNIGHT, pin_to=self.PIN)

        # The comparison the gate makes, on the artifacts the gate reads.
        for artifact in ("changes.json", "changes.xml"):
            self.assertEqual(
                fingerprint.normalize(before[artifact]),
                fingerprint.normalize(after[artifact]),
                f"{artifact} varies across a UTC date rollover",
            )

    def test_the_comparison_is_not_vacuous(self):
        """Events must actually be present, or the test above proves nothing."""
        built = build_feed(BEFORE_MIDNIGHT, pin_to=self.PIN)
        self.assertEqual(built["summary"]["new_event_count"], len(RECORDS))
        payload = json.loads(built["changes.json"].decode("utf-8"))
        self.assertEqual(len(payload["events"]), len(RECORDS))
        self.assertTrue(all(event["id"] for event in payload["events"]))

    def test_event_ids_are_left_opaque_rather_than_normalized(self):
        """fingerprint.py must not learn to blank out hashes (§8.4)."""
        built = build_feed(BEFORE_MIDNIGHT, pin_to=self.PIN)
        normalized = fingerprint.normalize(built["changes.json"]).decode("utf-8")
        payload = json.loads(built["changes.json"].decode("utf-8"))
        for event in payload["events"]:
            self.assertIn(event["id"], normalized)

    def test_the_pin_survives_timestamp_normalization(self):
        """A pinned stamp fingerprint.py could not normalize would leak the clock."""
        self.assertRegex(self.PIN, fingerprint.TIMESTAMP_RE)


class PinToolTests(unittest.TestCase):
    def test_only_the_top_level_field_is_replaced(self):
        text = catalog_text(BEFORE_MIDNIGHT, RECORDS)
        pinned = pin_generated_at.pin(text, "2026-08-17T00:00:00Z")
        payload = json.loads(pinned[pinned.index("{"):].strip().rstrip(";"))
        self.assertEqual(payload["generated_at"], "2026-08-17T00:00:00Z")
        for field in (
            "detail_enrichment_generated_at",
            "document_evidence_generated_at",
            "link_health_generated_at",
        ):
            self.assertEqual(payload[field], BEFORE_MIDNIGHT)

    def test_every_other_byte_is_untouched(self):
        text = catalog_text(BEFORE_MIDNIGHT, RECORDS)
        pinned = pin_generated_at.pin(text, "2026-08-17T00:00:00Z")
        self.assertEqual(
            text.replace(f'"generated_at": "{BEFORE_MIDNIGHT}"', "", 1),
            pinned.replace('"generated_at": "2026-08-17T00:00:00Z"', "", 1),
        )

    def test_a_missing_field_is_an_error_not_a_silent_pass(self):
        with self.assertRaises(ValueError):
            pin_generated_at.pin('globalThis.GRANT_CATALOG={"a":1};', "2026-08-17T00:00:00Z")

    def test_an_ambiguous_field_is_an_error(self):
        text = '{"generated_at":"x","nested":{"generated_at":"y"}}'
        with self.assertRaises(ValueError):
            pin_generated_at.pin(text, "2026-08-17T00:00:00Z")

    def test_a_non_iso_pin_is_refused(self):
        text = catalog_text(BEFORE_MIDNIGHT, RECORDS)
        for bad in ("2026-08-17", "not-a-time", "2026-08-17 00:00:00"):
            with self.assertRaises(ValueError):
                pin_generated_at.pin(text, bad)

    def test_the_cli_reports_failure_rather_than_writing_a_bad_copy(self):
        with tempfile.TemporaryDirectory() as tmp:
            source = Path(tmp) / "in.js"
            source.write_text('globalThis.GRANT_CATALOG={"a":1};', encoding="utf-8")
            destination = Path(tmp) / "out.js"
            self.assertEqual(
                pin_generated_at.main(
                    [str(source), str(destination), "2026-08-17T00:00:00Z"]
                ),
                1,
            )
            self.assertFalse(destination.exists())


class HermeticBuildWiringTests(unittest.TestCase):
    """The gate script must keep using the pin. Removing it re-opens D7."""

    def setUp(self):
        self.script = (ROOT / "tools" / "hermetic_build.sh").read_text(
            encoding="utf-8"
        )

    def test_the_pin_runs_before_the_change_feed(self):
        self.assertIn("tools/pin_generated_at.py", self.script)
        self.assertLess(
            self.script.index("tools/pin_generated_at.py"),
            self.script.index("scripts.build_changes"),
        )

    def test_build_changes_reads_the_pinned_copy_not_the_artifact(self):
        self.assertIn('--current "$OUT/.work/opportunities.pinned.js"', self.script)
        self.assertNotIn('--current "$OUT/opportunities.js"', self.script)

    def test_the_pinned_copy_stays_inside_the_excluded_work_directory(self):
        """.work/ is skipped by fingerprint.py, so the copy is never an artifact."""
        self.assertIn('"$OUT/.work/opportunities.pinned.js"', self.script)
        self.assertTrue(
            any(
                part.startswith(".")
                for part in Path(".work/opportunities.pinned.js").parts
            )
        )

    def test_the_pinned_stamp_is_a_normalizable_literal(self):
        for line in self.script.splitlines():
            if line.startswith("GENERATED_AT="):
                value = line.split("=", 1)[1].strip().strip('"')
                self.assertRegex(value, fingerprint.TIMESTAMP_RE)
                return
        self.fail("hermetic_build.sh no longer defines GENERATED_AT")


if __name__ == "__main__":
    unittest.main()
