import fs from 'node:fs';import path from 'node:path';import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';
import {openFundingFinder,runFundingSearch,mockHybrid} from '../e2e/helpers.mjs';
const root='outputs/team-recommender-stage3',read=p=>JSON.parse(fs.readFileSync(p)),packages=read('docs/team-recommender/receipts/stage3-routing-packages-v3.json').packages;
async function setup(page,cohort='rollout150',mode={}){
 const pkg=packages[cohort],dir=pkg.input_directory||root+'/assembled-'+cohort,directory=read(dir+'/directory.json'),context=read(dir+'/context.json'),requests=[],external=[],errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{requests.push({url:r.url(),method:r.method()});if(!r.url().startsWith('http://127.0.0.1:'))external.push(r.url());});
 await page.route('**/*',async route=>{const u=new URL(route.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname))return route.abort('blockedbyclient');return route.fallback();});
 await page.route('**/match_explorer.html*',async route=>{let html=fs.readFileSync('match_explorer.html','utf8');html=html.replace(/(<meta name="opportunity-team-generation" content=")[a-f0-9]+/,`$1${pkg.generation}`);await route.fulfill({contentType:'text/html',body:html});});
 await page.route('**/data/researcher_directory.js*',route=>route.fulfill({contentType:'text/javascript',body:'globalThis.RESEARCHER_DIRECTORY='+JSON.stringify(directory)+';'}));
 await page.route('**/data/opportunity_team_index.js*',route=>route.fulfill({contentType:'text/javascript',body:fs.readFileSync((pkg.package_directory||root+'/package-'+cohort)+'/data/opportunity_team_index.js')}));
 await page.route('**/data/team-recommender/*',async route=>{if(mode.delay)await new Promise(r=>setTimeout(r,mode.delay));const p=new URL(route.request().url()).pathname.slice(1),raw=fs.readFileSync((pkg.package_directory||root+'/package-'+cohort)+'/'+p);if(mode.unavailable)return route.fulfill({status:503,body:'Unavailable fixture'});await route.fulfill({contentType:p.endsWith('f32')?'application/octet-stream':'application/json',body:mode.corrupt?raw.subarray(1):raw});});
 await openFundingFinder(page);return {pkg,context,directory,requests,external,errors,team:()=>requests.filter(r=>/\/data\/team-recommender\/|\/assets\/team-(ingredients|recommender)\.js/.test(r.url)),paid:()=>requests.filter(r=>/embed|rerank|api\.anthropic|api\.openai|api\.voyage/i.test(r.url)&&!r.url.includes('embedding-schema'))};
}
const drawer=page=>page.locator('#team-builder');
async function openReal(page,id='359696',query='olfactory'){
 await runFundingSearch(page,query);const trigger=page.locator(`[data-opportunity-team="${id}"]`).first();await expect(trigger).toBeVisible();await trigger.click();await expect(drawer(page).locator('.opportunity-team-next')).toBeVisible();return trigger;
}
async function audit(page,info,label){const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();await info.attach(label,{body:Buffer.from(JSON.stringify({violations:a.violations,incomplete:a.incomplete})),contentType:'application/json'});expect(a.violations.filter(v=>['critical','serious'].includes(v.impact))).toEqual([]);}
for(const cohort of ['rollout50','rollout150'])test(`real ${cohort} routing: lazy cold/warm build, all candidates, options, edits, focus and accessibility`,async({page},info)=>{
 const p=await setup(page,cohort);expect(p.team()).toHaveLength(0);expect(await page.evaluate(()=>typeof TeamRecommender)).toBe('undefined');
 const trigger=await openReal(page);const d=drawer(page);await expect(d).toContainText('Coverage unconfirmed');await expect(d).not.toContainText('Direct evidence');expect(p.team()).toHaveLength(5);
 const before=p.paid().length;await expect.poll(()=>d.locator('[data-opportunity-team-remove]').count()).toBe(2);
 const count=await d.locator('[data-opportunity-team-variant]').count();expect(count).toBeLessThanOrEqual(8);if(count>1)await d.locator('[data-opportunity-team-variant]').last().click();
 const id=await d.locator('[data-opportunity-team-remove]').first().getAttribute('data-opportunity-team-remove');await d.locator('[data-opportunity-team-remove]').first().click();
 const select=d.locator('[data-opportunity-team-replacement]');await expect(select.locator(`option[value="${id}"]`)).toContainText('Previously selected');await select.selectOption(id);await d.locator('[data-opportunity-team-add-replacement]').click();
 while(await d.locator('[data-opportunity-team-remove]').count()<4){await select.selectOption({index:1});await d.locator('[data-opportunity-team-add-replacement]').click();}
 await expect(d).toContainText('4 of 4 team slots used');await expect(d.locator('[data-opportunity-team-add-replacement]')).toHaveCount(0);
 const href=await d.getByRole('link',{name:'Continue in Team Match'}).getAttribute('href');expect(new URL(href,'http://local/').searchParams.get('proposed').split(',')).toHaveLength(4);
 await audit(page,info,cohort+'-full-team');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await audit(page,info,cohort+'-mobile');
 await page.keyboard.press('Escape');await expect(d).not.toBeVisible();await expect(trigger).toBeFocused();await trigger.click();await expect(d.locator('.opportunity-team-next')).toBeVisible();expect(p.team()).toHaveLength(5);expect(p.paid().length).toBe(before);
 await info.attach('network.json',{body:Buffer.from(JSON.stringify(p)),contentType:'application/json'});expect(p.errors).toEqual([]);
});
test('native child chooser and all-member handoff preserve real source ownership',async({page},info)=>{
 const p=await setup(page,'rollout150');await runFundingSearch(page,'FOUNDATIONAL RESEARCH');const trigger=page.locator('[data-opportunity-team="344592"]').first();await expect(trigger).toBeVisible();await trigger.click();
 await expect(drawer(page)).toContainText('Choose a specific opportunity topic');const child=drawer(page).locator('[data-opportunity-team-scope="344592:ab-0009"]');await expect(child).toBeVisible();await child.click();await expect(drawer(page).locator('.opportunity-team-next')).toBeVisible();
 const href=await drawer(page).getByRole('link',{name:'Continue in Team Match'}).getAttribute('href');expect(new URL(href,'http://local').searchParams.get('opportunity')).toBe('344592:ab-0009');
 const ids=await drawer(page).locator('[data-opportunity-team-remove]').evaluateAll(ns=>ns.map(n=>n.getAttribute('data-opportunity-team-remove')));
 expect(ids.length).toBeGreaterThanOrEqual(2);const paid=p.paid().length;await drawer(page).getByRole('link',{name:'Continue in Team Match'}).click();await expect(page.locator('#pi-grid [data-member-entry]')).toHaveCount(ids.length);const handoffRequests=p.paid().slice(paid);expect(handoffRequests.every(r=>r.method==='POST'&&r.url.endsWith('/embed-query'))).toBe(true);expect(handoffRequests.length).toBeLessThanOrEqual(1);
 // The separate existing Team Match hosted-search request is intercepted, never paid.
 expect(p.requests.filter(r=>/opportunity_teams\.js/.test(r.url))).toHaveLength(0);await info.attach('network.json',{body:Buffer.from(JSON.stringify(p.requests)),contentType:'application/json'});
});
test('unavailable and mixed-generation assets fail without provider fallback and recover the preserved package',async({page},info)=>{
 const mode={unavailable:true},p=await setup(page,'rollout50',mode);await runFundingSearch(page,'olfactory');await page.locator('[data-opportunity-team="359696"]').first().click();await expect(drawer(page).locator('[data-opportunity-team-retry]')).toBeVisible();const paid=p.paid().length;
 mode.unavailable=false;await page.evaluate(()=>{OpportunityTeam.resetLoadForTest();globalThis.OPPORTUNITY_TEAM_INDEX.ingredients.sha256='0'.repeat(64);});await drawer(page).locator('[data-opportunity-team-retry]').click();await expect(drawer(page).locator('[data-opportunity-team-retry]')).toBeVisible();
 expect(p.paid().length).toBe(paid);await page.reload();await runFundingSearch(page,'olfactory');const afterSearch=p.paid().length,trigger=page.locator('[data-opportunity-team="359696"]').first();await trigger.click();await expect(drawer(page).locator('.opportunity-team-next')).toBeVisible();await expect(drawer(page).locator('[data-opportunity-team-remove]')).toHaveCount(2);expect(p.paid().length).toBe(afterSearch);await page.keyboard.press('Escape');await expect(trigger).toBeFocused();await info.attach('network.json',{body:Buffer.from(JSON.stringify(p.requests)),contentType:'application/json'});
});
test('real complete app distinguishes no-group and unprepared; no calls on retry or corrupt cache miss',async({page},info)=>{
 const mode={corrupt:true},p=await setup(page,'rollout150',mode);await runFundingSearch(page,'olfactory');await page.locator('[data-opportunity-team="359696"]').first().click();await expect(drawer(page).locator('[data-opportunity-team-retry]')).toBeVisible();const before=p.paid().length,oldRetry=await drawer(page).locator('[data-opportunity-team-retry]').elementHandle();await oldRetry.click();await expect.poll(()=>oldRetry.evaluate(n=>n.isConnected)).toBe(false);await expect(drawer(page).locator('[data-opportunity-team-retry]')).toBeVisible();
 mode.corrupt=false;await drawer(page).locator('[data-opportunity-team-retry]').click();await expect(drawer(page).locator('.opportunity-team-next')).toBeVisible();expect(p.paid().length).toBe(before);
 await page.keyboard.press('Escape');await openReal(page,'360946','Assay Validation High Quality');await expect(drawer(page)).toContainText('Insufficient internal role coverage');await expect(drawer(page).locator('[data-opportunity-team-remove]')).toHaveCount(0);
 const availability=await page.evaluate(()=>({unprepared:OpportunityTeam.hasAvailableScope({scopeId:'362551'}),prepared:OpportunityTeam.hasAvailableScope({scopeId:'360946'})}));expect(availability).toEqual({unprepared:false,prepared:true});await info.attach('network.json',{body:Buffer.from(JSON.stringify(p.requests)),contentType:'application/json'});
});
test('closed panels and changed generation reject delayed responses, fresh actions expire cached choices',async({page},info)=>{
 const mode={delay:250},p=await setup(page,'rollout150',mode);await runFundingSearch(page,'olfactory');const trigger=page.locator('[data-opportunity-team="359696"]').first();await trigger.click();await page.keyboard.press('Escape');await page.waitForTimeout(1200);await expect(drawer(page)).not.toBeVisible();await expect(drawer(page).locator('.opportunity-team-panel')).toHaveCount(0);
 mode.delay=0;await trigger.click();await expect(drawer(page).locator('.opportunity-team-next')).toBeVisible();const paid=p.paid().length;
 await page.clock.setFixedTime(new Date('2035-09-30T12:00:00Z'));await drawer(page).locator('[data-opportunity-team-remove]').first().click();await expect(drawer(page)).toContainText(/no longer current|temporarily unavailable/);await expect(drawer(page).locator('[data-opportunity-team-remove]')).toHaveCount(0);
 await page.clock.setFixedTime(new Date('2026-09-10T12:00:00Z'));await page.keyboard.press('Escape');await trigger.click();await expect(drawer(page).locator('.opportunity-team-next')).toBeVisible();await page.evaluate(()=>document.querySelector('meta[name="opportunity-team-generation"]').content='c'.repeat(64));await drawer(page).locator('[data-opportunity-team-remove]').first().click();await expect(drawer(page).locator('[data-opportunity-team-retry]')).toBeVisible();expect(p.paid().length).toBe(paid);await info.attach('network.json',{body:Buffer.from(JSON.stringify(p.requests)),contentType:'application/json'});
});
test('real heldout rendering uses zero, one and eight useful options without padding',async({page},info)=>{
 const p=await setup(page,'holdout_effective');const cases=[['320087','Security and Preparedness',8],['302273','Combinatorics',1],['360946','Assay Validation High Quality',0]],seen=[];
 for(const [id,query,options]of cases){const trigger=await openReal(page,id,query),d=drawer(page),buttons=await d.locator('[data-opportunity-team-variant]').count();expect(buttons).toBe(options>1?options:0);expect(await d.locator('[data-opportunity-team-remove]').count()).toBe(options?2:0);if(options===8){const first=await d.locator('[data-opportunity-team-variant]').first().textContent();await d.locator('[data-opportunity-team-variant]').last().click();await d.locator('[data-opportunity-team-variant]').first().click();expect(await d.locator('[data-opportunity-team-variant]').first().textContent()).toBe(first);}seen.push({id,options,buttons});await page.keyboard.press('Escape');await expect(trigger).toBeFocused();}
 await info.attach('real-option-cardinality.json',{body:Buffer.from(JSON.stringify({seen,requests:p.requests})),contentType:'application/json'});
});
