"""Subtopic cache: record construction, diff-stable I/O, and the backfill gate.

Three jobs, and deliberately no fourth:

1. Turn accepted :class:`~scripts.subtopic_segmentation.Subtopic` spans into
   §5.1 catalog records.
2. Read and write ``data/subtopics.js`` with the §5.4 serialization
   that keeps a daily commit small.
3. Answer :func:`needs_subtopic_extraction`, which is what makes the ~1,400
   already-cached documents get subtopics at all (§8.3).

Identity matching (``match_subtopics``, ``normalize_code``,
``title_fingerprint``) and term maps (``build_term_map``) already live in
``subtopic_segmentation`` -- they landed there during package B because they
are pure functions over spans and subtopic dicts with no cache involvement.
This module imports them rather than restating them. §18.1 lists them under
C1; that is a bookkeeping difference, not a design one.

Nothing here imports ``extract_document_evidence``: that module imports *this*
one at a flag-guarded call site, and the dependency runs one way only.

See docs/TOPIC_LAYER_PLAN.md §5.1, §5.4, §8.3.
"""

from __future__ import annotations

import json
from pathlib import Path
import tempfile

from scripts.subtopic_segmentation import MAX_TERMS, extractor_version, match_subtopics


CACHE_SCHEMA_VERSION = 1
DEFAULT_CACHE = Path("data/subtopics.js")
SIDECAR_GLOBAL = "globalThis.SUBTOPIC_CATALOG="
SIDECAR_HEADER = "/* Generated by scripts/build_subtopics.py. Do not edit by hand. */\n"

# --- §5.1 provenance ladder ---------------------------------------------------
#
# Ordered by how much this project had to guess. **The test is how the
# parent->child relationship was ESTABLISHED, never the document's format and
# never which layer happened to read it.**
#
#   native      the agency published the children as data -- a table, an
#               explicit child list, an API, one row per child
#   referenced  an agency program page off the solicitation asserts that these
#               programmes belong to this parent
#   inline      the solicitation itself states the fundable child relationship
#               -- text saying applicants apply to one of these, members named
#   inferred    this project established it, from structure or position, with
#               no such statement to rely on
#
# **Generic structural or pattern extraction is `inferred` even when it runs on
# an official solicitation.** `structural_siblings` over a bookmark tree is
# inferred: a bookmark tree is a layout artifact this project reads as a
# hierarchy, and the notice never says those nodes are the fundable units. The
# same holds for every ordinal family match, and for PACER's topics won from a
# secondary attachment. Being in an authoritative document does not make an
# inference authoritative.
#
# A family match is EVIDENCE for `inline`, not sufficient for it: the notice has
# to do the asserting. Nothing in the pipeline can currently establish that, so
# `classify_provenance` returns `inferred` for every segmentation result today
# and `inline` is reachable only by an explicit caller override. That is
# deliberate -- the ladder fails downward (§5.1).
NATIVE = "native"
REFERENCED = "referenced"
INLINE = "inline"
INFERRED = "inferred"
PROVENANCE_VALUES = (NATIVE, REFERENCED, INLINE, INFERRED)

# The ceiling each rung may reach. Not the value: §5.1 is explicit that
# provenance BOUNDS confidence and does not set it, because `native` and
# `referenced` have their own failure modes -- a restyled table, a stale page, a
# mis-linked parent -- that a rung cannot vouch for.
PROVENANCE_CEILING = {
    NATIVE: "high",
    REFERENCED: "high",
    INLINE: "high",
    INFERRED: "medium",     # never high, whatever the method (§6.3a, §5.1)
}
_CONFIDENCE_ORDER = ("low", "medium", "high")


def classify_provenance(result, *, document=None, override=None):
    """Which rung established this parent->child relationship (§5.1).

    `override` is how a `native` or `referenced` adapter declares its own
    provenance; it is validated rather than trusted blindly. Everything the
    segmentation pipeline produces is `inferred`, including outline-structural
    and every ordinal family, because the notice asserted nothing -- this
    project did.
    """
    if override is not None:
        if override not in PROVENANCE_VALUES:
            raise ValueError(f"unknown provenance {override!r}")
        return override
    return INFERRED


def cap_confidence(confidence, provenance):
    """Lower `confidence` to the rung's ceiling. Never raises it.

    A record is never promoted for sitting on a high rung -- §5.1's "provenance
    is not a shortcut for validation". `native`'s own structure checks and
    `referenced`'s parent-match/staleness checks belong to their adapters, which
    pass the earned value in; this only enforces the bound.
    """
    ceiling = PROVENANCE_CEILING.get(provenance, "medium")
    if confidence not in _CONFIDENCE_ORDER:
        return confidence
    if _CONFIDENCE_ORDER.index(confidence) <= _CONFIDENCE_ORDER.index(ceiling):
        return confidence
    return ceiling

# --- §7.1 publication eligibility --------------------------------------------
#
# **Three concepts, and Cov6 exists partly because two of them had been encoded
# in one field.** They are kept apart deliberately:
#
#   provenance (`subtopic_source`)  WHO asserted the parent->child relationship.
#                                   §5.1's ladder. Never changed by a verdict.
#   confidence                      HOW WELL THIS RUN READ IT. Earned by the
#                                   segmentation method, bounded by the rung's
#                                   ceiling, lowered by `_demote()` when the
#                                   document is secondary to the announcement.
#                                   **Not a review flag and not a permission.**
#   review state (`cov4_*`)         WHAT COV4 DECIDED, on two axes. Recorded by
#                                   `subtopic_cov4.apply_gate`.
#   publication eligibility         DERIVED FROM ALL THREE, right here. Stored
#                                   nowhere, so it cannot drift from its inputs.
#
# The rule is §7.1's, unchanged and now stated once in code rather than in prose:
#
#     publish = confidence == "high"
#            OR (confidence in {"medium", "low"}
#                AND an approval exists for this subtopic_id
#                AND that approval's document_sha256 == the current document's)
#
# with Cov4's fail-closed contract layered on top for the rungs Cov4 judges.
PUBLISHABLE = "publishable"
REVIEW = "review"

# Cov4's field names and verdict values, restated rather than imported:
# `subtopic_cov4` imports *this* module, so importing it back would be a cycle.
# `tests/test_subtopic_cov6.py` asserts these equal `subtopic_cov4`'s constants,
# so the restatement cannot drift silently.
_COV4_JUDGED_PROVENANCE = frozenset({INLINE, INFERRED})
_COV4_OWNED = "owned"
_COV4_ACCEPT = "accept"


def publication_eligibility(record, *, approvals=None):
    """May this subtopic reach a PI unattended? Returns ``(state, reason)``.

    **This function is the single authority on the question**, and it is
    deliberately a pure predicate over a record: P9's merge applies it, no
    caller stores its answer, and nothing downstream may re-derive publication
    from `confidence` alone. That last point is the fail-closed hole Cov6
    closed -- `inline`'s ceiling is `high`, so a bare ``confidence == "high"``
    test would publish an `inline` span whose classifier call had failed.

    `approvals` is the reviewed-labels map §7.1 describes, keyed by
    `subtopic_id`, each value carrying a `status` and the `document_sha256` the
    label was made against. **Building the surface that produces it is P9/P10
    work and is not done here**; Cov6's job is to define the state it consumes.
    An approval whose hash no longer matches the record's `source_document_hash`
    is stale and does not count -- which is the whole reason the hash is in the
    payload, because a changed notice must re-queue rather than inherit
    yesterday's judgment.
    """
    # Cov4's two axes first: an unresolved or failed classification is not a
    # passing one, whatever tier the span carries and whatever a human said.
    if record.get("subtopic_source") in _COV4_JUDGED_PROVENANCE:
        if record.get("cov4_ownership") != _COV4_OWNED:
            return REVIEW, f"cov4_ownership_{record.get('cov4_ownership')}"
        if record.get("cov4_fundability") != _COV4_ACCEPT:
            return REVIEW, f"cov4_fundability_{record.get('cov4_fundability')}"

    approval = (approvals or {}).get(record.get("subtopic_id"))
    if approval:
        if str(approval.get("status")) != "approve":
            return REVIEW, "approval_not_granted"
        if approval.get("document_sha256") != record.get("source_document_hash"):
            # §7.1: the notice moved under the label, so the label is void.
            return REVIEW, "approval_stale"
        return PUBLISHABLE, "approved"

    if record.get("confidence") == "high":
        return PUBLISHABLE, "high_confidence"
    return REVIEW, f"tier_{record.get('confidence')}"


def is_publishable(record, *, approvals=None):
    """:func:`publication_eligibility` as a boolean, for filtering."""
    return publication_eligibility(record, approvals=approvals)[0] == PUBLISHABLE


# Fields whose change means the record genuinely moved. `last_verified` is
# excluded on purpose -- see `_content_key`.
VOLATILE_FIELDS = ("last_verified",)


def needs_subtopic_extraction(entry, *, enabled, extractor_version):
    """True when a cached entry has no usable subtopic result for this extractor.

    Backfill and version-bump reprocessing both route through here. Without it
    the three §4 skip gates mean only documents that happen to change get
    segmented, and the ~1,400 already-cached documents never do -- the feature
    appears to work on a handful of records and silently never backfills.
    """
    if not enabled:
        return False
    if entry is None:
        return False                      # a full extraction is already happening
    if "subtopics" not in entry:
        return True                       # never attempted
    if entry.get("subtopic_extractor_version") != extractor_version:
        return True                       # toolchain or pattern set moved (§6.1)
    return False


def subtopic_id_for(parent_opportunity_id, subtopic_code_norm):
    """Stable child identity anchored only to the parent's canonical id."""
    return f"{parent_opportunity_id}:{subtopic_code_norm}"


def source_role(document):
    """Truthful reviewer-facing role, orthogonal to ownership/provenance."""
    kind = (document or {}).get("source_kind")
    if kind in {"primary_notice", "authoritative_notice"}:
        return "authoritative_announcement"
    if kind == "secondary_attachment":
        return "secondary_attachment"
    if kind == "attached_source":
        return "attached_source"
    if kind == "referenced_page":
        return "referenced_program_page"
    if kind in {"agency_notice", "subtopic_agency_notice"}:
        return "agency_page"
    return "unknown"


def build_records(
    parent,
    result,
    *,
    document=None,
    as_of=None,
    provenance=None,
):
    """§5.1 records for one parent, from an accepted SegmentationResult.

    Fields inherited from the parent (§5.5) -- agency, instrument, eligibility,
    award range, the deadline used for filtering -- are deliberately NOT copied
    here. The merge in package E attaches them; duplicating them would put two
    copies of the same fact in the catalog and let them disagree.

    `provenance` is the §5.1 rung, passed in by a `native` or `referenced`
    adapter. Left None it resolves to `inferred`, which is correct for
    everything the segmentation pipeline produces. `segmentation_method` stays
    orthogonal: provenance says who asserted the relationship, the method says
    how this pipeline obtained the spans, and neither is derived from the other.
    """
    document = document or {}
    rung = classify_provenance(result, document=document, override=provenance)
    confidence = cap_confidence(result.confidence, rung)
    parent_number = (
        parent.get("opportunity_number")
        or parent.get("opportunity_id")
        or ""
    )
    parent_id = str(parent.get("opportunity_id") or parent_number)
    version = (result.diagnostics or {}).get("extractor_version") or extractor_version()

    records = []
    for subtopic in result.subtopics:
        identifier = subtopic_id_for(parent_id, subtopic.subtopic_code_norm)
        records.append(
            {
                "record_type": "subtopic",
                "child_type": "subject",
                "subtopic_id": identifier,
                # The browser derives identity from opportunity_id ||
                # opportunity_number (assets/app.js recordId), so a child with
                # neither is invisible to half the system.
                "opportunity_id": identifier,
                "parent_id": parent_id,
                "parent_opportunity_number": parent_number,
                "subtopic_code": subtopic.subtopic_code,
                "subtopic_code_norm": subtopic.subtopic_code_norm,
                "subtopic_ordinal": subtopic.subtopic_ordinal,
                "ordinal_label": subtopic.ordinal_label,
                "title": subtopic.title,
                "title_fingerprint": subtopic.title_fingerprint,
                "summary": subtopic.summary,
                "subtopic_terms": dict(subtopic.subtopic_terms),
                "subtopic_source": rung,
                # The catalog's own vocabulary, never a private one:
                # currentness.record_is_current accepts only posted/forecasted,
                # so a child emitting anything else is filtered out of every
                # feed and every browser view as invalid_status.
                "status": parent.get("status"),
                "topic_areas": list(subtopic.topic_areas),
                "program_area_labels": list(subtopic.program_area_labels),
                "page_start": subtopic.page_start,
                "page_end": subtopic.page_end,
                "evidence_anchor": subtopic.anchor
                or (f"p{subtopic.page_start}" if subtopic.page_start else None),
                "source_document_url": document.get("url"),
                "source_document_hash": document.get("sha256"),
                "source_role": source_role(document),
                "segmentation_method": result.method,
                "confidence": confidence,
                "pattern_family": result.family,
                "own_deadline": subtopic.own_deadline,
                "own_deadline_is_advisory": True,
                "first_seen": as_of,
                "last_verified": as_of,
                "extractor_version": version,
            }
        )
    return records


def build_structured_records(
    parent,
    children,
    *,
    document,
    as_of,
    provenance,
    confidence,
    method,
    source_version=None,
):
    """Build records from an agency-declared child list, without segmentation.

    ``children`` is deliberately a tiny adapter contract: code, title and
    optional summary/terms/evidence/hierarchy fields. Source-specific parsers
    retain their stable codes while every common publication field is written
    in one place.
    """
    from scripts.subtopic_segmentation import (
        build_term_map,
        normalize_code,
        program_area_fields,
        summarize,
        title_fingerprint,
    )

    parent_id = str(
        parent.get("opportunity_id")
        or parent.get("opportunity_number")
        or ""
    )
    parent_number = parent.get("opportunity_number") or parent_id
    rung = classify_provenance(None, document=document, override=provenance)
    earned = cap_confidence(confidence, rung)
    built = []
    for ordinal, child in enumerate(children, start=1):
        code = str(child.get("code") or ordinal).strip()
        code_norm = str(child.get("code_norm") or normalize_code(code))
        title = str(child.get("title") or "").strip()[:200]
        full_text = str(child.get("text") or child.get("summary") or title)
        labels, topics = program_area_fields(full_text)
        record = {
            "record_type": "subtopic",
            "child_type": "subject",
            "subtopic_id": subtopic_id_for(parent_id, code_norm),
            "opportunity_id": subtopic_id_for(parent_id, code_norm),
            "parent_id": parent_id,
            "parent_opportunity_number": parent_number,
            "subtopic_code": code,
            "subtopic_code_norm": code_norm,
            "subtopic_ordinal": int(child.get("ordinal") or ordinal),
            "ordinal_label": str(child.get("ordinal_label") or code),
            "title": title,
            "title_fingerprint": title_fingerprint(title),
            "summary": summarize(str(child.get("summary") or full_text)),
            "subtopic_terms": dict(child.get("terms") or build_term_map(full_text)),
            "subtopic_source": rung,
            "status": parent.get("status"),
            "topic_areas": list(child.get("topic_areas") or topics),
            "program_area_labels": list(
                child.get("program_area_labels") or labels
            ),
            "page_start": child.get("page_start"),
            "page_end": child.get("page_end"),
            "evidence_anchor": child.get("anchor"),
            "source_document_url": (document or {}).get("url"),
            "source_document_hash": (document or {}).get("sha256"),
            "source_role": source_role(document),
            "source_version": source_version,
            "segmentation_method": method,
            "confidence": earned,
            "pattern_family": None,
            "own_deadline": None,
            "own_deadline_is_advisory": True,
            "first_seen": as_of,
            "last_verified": as_of,
            "extractor_version": extractor_version(),
        }
        for field in ("group_id", "parent_subtopic_id"):
            if child.get(field):
                record[field] = child[field]
        for field in (
            "native_status",
            "native_deadline_text",
            "division",
            "amended",
            "child_source_url",
        ):
            if child.get(field) not in (None, ""):
                record[field] = child[field]
        built.append(record)
    return built


def _content_key(record):
    """Everything except the volatile fields, for change detection (§5.4)."""
    return {
        key: value
        for key, value in record.items()
        if key not in VOLATILE_FIELDS and key != "first_seen"
    }


def upsert_parent(cache, parent_id, records, *, as_of, reason=None, method=None):
    """Merge one parent's subtopics into the cache. Returns True if it changed.

    `subtopic_id` and `first_seen` are assigned once at first sight and carried
    forward through title-first matching, so identity survives renumbering,
    retitling and repagination (§5.3). `last_verified` moves **only** when
    something else did -- otherwise the timestamp alone rewrites the file every
    night and the repository grows for no reason (§5.4).
    """
    entries = cache.setdefault("records", {})
    previous = entries.get(parent_id) or {}
    old_records = list(previous.get("subtopics") or [])

    merged, changed = [], False
    for before, after in match_subtopics(old_records, list(records)):
        if after is None:
            changed = True                     # removed
            continue
        if before is None:
            merged.append(after)               # added
            changed = True
            continue
        carried = dict(after)
        carried["subtopic_id"] = before.get("subtopic_id", after["subtopic_id"])
        carried["opportunity_id"] = carried["subtopic_id"]
        carried["first_seen"] = before.get("first_seen") or after.get("first_seen")
        if _content_key(before) == _content_key(carried):
            carried["last_verified"] = before.get("last_verified")
        else:
            changed = True
        merged.append(carried)

    merged.sort(key=lambda item: (item.get("subtopic_ordinal") or 0,
                                  item.get("subtopic_code_norm") or ""))

    entry = {
        "subtopics": merged,
        "subtopic_count": len(merged),
        "segmentation_method": method,
        "subtopic_extractor_version": extractor_version(),
    }
    if reason:
        entry["subtopic_reason"] = reason

    if previous.get("subtopics") is None and not merged and not reason:
        # Nothing to record and nothing was there before.
        return False

    unchanged = (
        previous
        and previous.get("subtopic_reason") == entry.get("subtopic_reason")
        and previous.get("segmentation_method") == entry.get("segmentation_method")
        and previous.get("subtopic_extractor_version")
        == entry.get("subtopic_extractor_version")
        and not changed
    )
    if unchanged:
        return False

    entries[parent_id] = entry
    return True


def empty_cache():
    return {"schema_version": CACHE_SCHEMA_VERSION, "records": {}}


def retain_current_parents(cache, current_parent_ids):
    """P9.3: the sidecar has no currentness axis beyond parent membership."""
    current = {str(identifier) for identifier in current_parent_ids}
    entries = cache.setdefault("records", {})
    removed = sorted(set(entries) - current)
    cache["records"] = {
        parent: entry for parent, entry in entries.items() if parent in current
    }
    return removed


def _bounded_terms(terms):
    cleaned = []
    for term, frequency in (terms or {}).items():
        try:
            frequency = int(frequency)
        except (TypeError, ValueError):
            continue
        if term and frequency > 0:
            cleaned.append((str(term), frequency))
    cleaned.sort(key=lambda item: (-item[1], item[0]))
    return dict(cleaned[:MAX_TERMS])


def sidecar_payload(cache, *, approvals=None):
    """Public/review storage plus its compact, independent child BM25 index."""
    parents = {}
    flat = []
    searchable = []
    for parent, entry in sorted((cache.get("records") or {}).items()):
        children = []
        for child in sorted(
            entry.get("subtopics") or [],
            key=lambda item: (
                item.get("subtopic_ordinal") or 0,
                item.get("subtopic_code_norm") or "",
                item.get("subtopic_id") or "",
            ),
        ):
            stored = dict(child)
            stored["subtopic_terms"] = _bounded_terms(child.get("subtopic_terms"))
            state, reason = publication_eligibility(stored, approvals=approvals)
            stored["publication_state"] = state
            stored["publication_reason"] = reason
            children.append(stored)
            flat.append(stored)
            if state == PUBLISHABLE and stored.get("child_type") == "subject":
                searchable.append(stored)
        parents[parent] = {
            **entry,
            "subtopics": children,
            "subtopic_count": len(children),
        }

    record_ids = [child.get("subtopic_id") for child in searchable]
    lengths = [sum(child.get("subtopic_terms", {}).values()) for child in searchable]
    postings = {}
    for document_id, child in enumerate(searchable):
        for term, frequency in child.get("subtopic_terms", {}).items():
            postings.setdefault(term, []).extend((document_id, frequency))
    payload = {
        "schema_version": cache.get("schema_version", CACHE_SCHEMA_VERSION),
        "parent_count": sum(bool(entry["subtopics"]) for entry in parents.values()),
        "record_count": len(flat),
        "records": parents,
        "search_index": {
            "document_count": len(searchable),
            "average_document_length": (
                sum(lengths) / len(lengths) if lengths else 0
            ),
            "document_lengths": lengths,
            "record_ids": record_ids,
            "postings": {term: postings[term] for term in sorted(postings)},
        },
        "searchable_record_count": len(searchable),
    }
    if cache.get("generation"):
        payload["generation"] = cache["generation"]
    return payload


def read_cache(path=DEFAULT_CACHE):
    path = Path(path)
    if not path.exists():
        return empty_cache()
    try:
        text = path.read_text(encoding="utf-8")
        if SIDECAR_GLOBAL in text:
            text = text.split(SIDECAR_GLOBAL, 1)[1].strip()
            if text.endswith(";"):
                text = text[:-1]
        payload = json.loads(text)
    except (ValueError, OSError):
        return empty_cache()
    if not isinstance(payload, dict):
        return empty_cache()
    payload.setdefault("schema_version", CACHE_SCHEMA_VERSION)
    payload.setdefault("records", {})
    return payload


def write_cache(cache, path=DEFAULT_CACHE):
    """Write with the §5.4 serialization.

    This file's style deliberately differs from every other file in data/. The
    existing caches are minified; this one is indented and key-sorted because
    it is the only committed artifact whose *line-level* diff a human reads
    when triaging a phantom-amendment flood. A minified 20,000-record file
    produces a one-line diff that tells you nothing.

    Records are sorted by (parent_opportunity_number, subtopic_ordinal), and
    written through a temp file with newline="\\n" so the bytes are LF on every
    platform -- matching how write_catalog and write_cache already behave in
    extract_document_evidence.
    """
    path = Path(path)
    payload = sidecar_payload(cache)
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        newline="\n",
        dir=str(path.parent),
        delete=False,
    ) as handle:
        handle.write(SIDECAR_HEADER)
        handle.write(SIDECAR_GLOBAL)
        json.dump(payload, handle, sort_keys=True, indent=1, ensure_ascii=False)
        handle.write(";\n")
        temporary = Path(handle.name)
    temporary.replace(path)
    return path


def cache_metrics(cache):
    """Counts for the §8.3 insertion-4 diagnostics block."""
    entries = (cache.get("records") or {}).values()
    subtopic_count = sum(len(entry.get("subtopics") or []) for entry in entries)
    reasons = {}
    methods = {}
    confidences = {}
    # §18.1 Cov6. Reported next to the tiers rather than instead of them,
    # because they answer different questions: the tier says how well the run
    # read the document, and this says whether anything may reach a PI without
    # a human. A build where every span is `medium` and every span is `review`
    # is the expected steady state for generic inference, not a fault.
    publication = {}
    publication_reasons = {}
    for entry in entries:
        reason = entry.get("subtopic_reason")
        if reason:
            reasons[reason] = reasons.get(reason, 0) + 1
        method = entry.get("segmentation_method")
        if method:
            methods[method] = methods.get(method, 0) + 1
        for record in entry.get("subtopics") or []:
            level = record.get("confidence")
            if level:
                confidences[level] = confidences.get(level, 0) + 1
            state, reason = publication_eligibility(record)
            publication[state] = publication.get(state, 0) + 1
            publication_reasons[reason] = publication_reasons.get(reason, 0) + 1
    return {
        "subtopic_parent_count": sum(
            1 for entry in entries if entry.get("subtopics")
        ),
        "subtopic_record_count": subtopic_count,
        "subtopic_rejection_reasons": dict(sorted(reasons.items())),
        "subtopic_methods": dict(sorted(methods.items())),
        "subtopic_confidence_counts": dict(sorted(confidences.items())),
        "subtopic_publication_counts": dict(sorted(publication.items())),
        "subtopic_publication_reasons": dict(sorted(publication_reasons.items())),
    }
