import fs from 'node:fs';import os from 'node:os';import assert from 'node:assert/strict';import {chromium} from '@playwright/test';
const browser=await chromium.launch({headless:true}),observations=[];
for(const cohort of ['rollout50','rollout150'])for(let sample=0;sample<5;sample++){
 const context=await browser.newContext({extraHTTPHeaders:{'x-post-audit-cohort':cohort}}),page=await context.newPage(),requests=[];let phase='startup';
 page.on('request',r=>requests.push({url:r.url(),phase}));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.goto('http://127.0.0.1:8771/match_explorer.html?gate4-e2e=1');await page.waitForFunction(()=>globalThis.OpportunityTeam&&globalThis.RESEARCHER_DIRECTORY);await page.waitForFunction(()=>globalThis.GRANT_CATALOG_METADATA);await page.evaluate(()=>FUNDING_CATALOG_LOADER.ensureCatalogReady());
 assert(!requests.some(r=>/team_ingredients|shared-team-engine/.test(r.url)));
 const cdp=await context.newCDPSession(page);await cdp.send('HeapProfiler.collectGarbage');const before=await cdp.send('Runtime.getHeapUsage');
 await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:20e6/8,uploadThroughput:20e6/8});
 phase='cold';const cold=await page.evaluate(async()=>{const start=performance.now();globalThis.measureData=await OpportunityTeam.loadData();const loaded=performance.now();globalThis.measureEngine=OpportunityTeam.create(measureData);return {start,load_ms:loaded-start,create_ms:performance.now()-loaded,statistics:measureEngine.statistics(),resources:performance.getEntriesByType('resource').filter(r=>/team_ingredients|shared-team-engine|team-matcher|subtopics/.test(r.name)).map(r=>({name:r.name,duration:r.duration,responseEnd:r.responseEnd,encoded:r.encodedBodySize,decoded:r.decodedBodySize,transfer:r.transferSize}))};});
 assert.equal(cold.statistics.fits,0);assert.equal(cold.statistics.optimizations,0);
 await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
 phase='prepared';const timing=await page.evaluate(()=>{const e=measureEngine,record=GRANT_CATALOG.opportunities.find(r=>r.opportunity_id==='344592'),input={scopeId:'344592:ab-0035',parentId:'344592',record,now:new Date()},start=performance.now(),decision=e.resolveScope(input),fit=performance.now();if(!decision.ok)throw Error(decision.reason);let state=e.proposal(decision.opportunity);const view=e.proposalView(state),options=e.proposalOptions(state),end=performance.now(),warm=[],edit=[];for(let i=0;i<10;i++){const t=performance.now();e.runAction(input,()=>{e.proposal(decision.opportunity);e.proposalView(state);e.proposalOptions(state);});warm.push(performance.now()-t);}for(let i=0;i<5;i++){const id=state.selectedIds[0],t=performance.now();e.runAction(input,()=>{state=e.removeMember(state,id);e.proposalOptions(state);state=e.addReplacement(state,id);e.proposalView(state);});edit.push(performance.now()-t);}return{scope:input.scopeId,fit_ms:fit-start,composition_ms:end-fit,post_input_ms:end-start,warm_ms:warm,edit_ms:edit,members:state.selectedIds.length,options:options.length,view_members:view.selected.length,statistics:e.statistics()};});
 const high=await cdp.send('Runtime.getHeapUsage');await cdp.send('HeapProfiler.collectGarbage');const retained=await cdp.send('Runtime.getHeapUsage');assert.equal(requests.filter(r=>r.phase!=='startup'&&!r.url.startsWith('http://127.0.0.1:8771/')).length,0);
 observations.push({cohort,sample,cold,timing,heap_before:before,heap_sampled_after_actions:high,heap_retained:retained,retained_delta_bytes:retained.usedSize-before.usedSize,network:requests});fs.writeFileSync('outputs/team-recommender-post-audit/browser-resource-samples.json',JSON.stringify(observations,null,2));console.log(cohort,sample,JSON.stringify({load:cold.load_ms,fit:timing.fit_ms,compose:timing.composition_ms,warm:Math.max(...timing.warm_ms),edit:Math.max(...timing.edit_ms)}));await context.close();
}
const result={version:'post-audit-real-browser-resources-v2',clock:'Native Date and performance APIs; prior v1 used Playwright clock which omits Resource Timing entries',browser:await browser.version(),os:os.release(),cpu:os.cpus()[0].model,logical_cpus:os.cpus().length,memory_bytes:os.totalmem(),network:'Local gzip HTTP; cold ingredient phase at CDP 20Mbps/150ms; no CPU throttle',physical_mobile:'NOT RUN',peak_memory:'NOT MEASURED; only sampled post-action and retained after explicit GC',observations};await browser.close();fs.writeFileSync('docs/team-recommender/post-audit/browser-resources-v2.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});
