// Source-only inventory/selection: never scores a profile or reads judge results.
import fs from 'node:fs';import vm from 'node:vm';import {createHash} from 'node:crypto';
import {buildSharedPackage,resolveSharedScopes} from './build_shared_team_package.mjs';
const DOC='docs/team-recommender/post-audit',OUT='outputs/team-recommender-post-audit',read=p=>JSON.parse(fs.readFileSync(p));
const sha=v=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex'),clock='2026-09-11T12:00:00Z';
const c=vm.createContext({Date});for(const p of ['assets/submission-schedule.js','assets/search-query.js','assets/search-retrieval.js','assets/team-matcher.js','data/opportunities.js','data/subtopics.js','data/researcher_directory.js','data/faculty_matches.js','data/opportunity_team_index.js'])vm.runInContext(fs.readFileSync(p,'utf8'),c);
const catalog=c.GRANT_CATALOG,child=c.FUNDING_RETRIEVAL.createChildCatalog(c.SUBTOPIC_CATALOG),parents=new Map(catalog.opportunities.map(r=>[r.opportunity_id,r])),children=new Map(child.opportunities.map(r=>[r.opportunity_id,r]));
const original=read('docs/team-recommender/manifests/rollout.json'),groups=read('docs/team-recommender/manifests/source-group-amendment-c2-f92fc5995a0a1ac0.json'),metadata=read('docs/team-recommender/manifests/source-groups.json'),history=read('docs/team-recommender/manifests/historical-exposure.json');
const group=id=>groups.source_group_map[id]||id,meta=new Map(metadata.records.map(r=>[r.id,r]));
const old=c.OPPORTUNITY_TEAM_INDEX.scopes,excludedParents=new Set([...history.excluded_parent_ids,...groups.development_scopes.map(r=>r.parent_id),...groups.holdout_scopes.map(r=>r.parent_id),...old.map(r=>r.parent_id)]),excludedGroups=new Set([...excludedParents].map(group));
const match=c.FUNDING_TEAM_MATCHER.create(catalog,c.FACULTY_MATCHES,c.FUNDING_SEARCH_QUERY,{now:new Date(clock)}),prepared=new Map(match.records.map(r=>[r.id,r]));
const independent=id=>!excludedGroups.has(group(id))&&!history.excluded_parent_ids.some(x=>id===x||id.startsWith(x+':'));
const sourceCandidate=r=>meta.get(r.opportunity_id)?.source_candidate===true&&!/email/i.test(r.source||'')&&r.description?.length>100;
// A native publishable scientific child is evaluated on its own projection.
// The old parent-synopsis heuristic can call a training umbrella non-scientific;
// that is not an authority to discard its already-published research children.
const childCandidates=child.opportunities.filter(r=>independent(r.parent_id)&&c.FUNDING_RETRIEVAL.recordIsCurrent(parents.get(r.parent_id),new Date(clock))
  && c.FUNDING_RETRIEVAL.recordIsCurrent(r,new Date(clock))&&!/email/i.test(parents.get(r.parent_id)?.source||'')&&r.description?.length>100);
const childGroups=[...new Set(childCandidates.map(r=>group(r.parent_id)))].sort((a,b)=>sha('post-audit-child|'+a).localeCompare(sha('post-audit-child|'+b)));
const selectedChildren=[];for(const gid of childGroups)for(const r of childCandidates.filter(r=>group(r.parent_id)===gid).sort((a,b)=>a.opportunity_id.localeCompare(b.opportunity_id))){if(selectedChildren.length<6)selectedChildren.push(r);}
const selectedGroupIds=new Set(selectedChildren.map(r=>group(r.parent_id))),selected=[];
const eligible=catalog.opportunities.filter(r=>independent(r.opportunity_id)&&sourceCandidate(r)&&prepared.has(r.opportunity_id)&&!prepared.get(r.opportunity_id).isBroad);
const buckets=new Map();for(const r of eligible){const family=meta.get(r.opportunity_id).family;const bucket=buckets.get(family)||[];bucket.push(r);buckets.set(family,bucket);}
for(const b of buckets.values())b.sort((a,b)=>sha('post-audit-sources-v1|'+a.opportunity_id).localeCompare(sha('post-audit-sources-v1|'+b.opportunity_id)));
while(selectedGroupIds.size<24){let added=false;for(const family of [...buckets.keys()].sort()){const b=buckets.get(family);let r;while(b.length&&!r){const next=b.shift();if(!selectedGroupIds.has(group(next.opportunity_id)))r=next;}if(r&&selectedGroupIds.size<24){selected.push(r);selectedGroupIds.add(group(r.opportunity_id));added=true;}}if(!added)break;}
const reserveFor=id=>({id,parent_id:children.get(id)?.parent_id||id});
const sample=[...selected.map(r=>reserveFor(r.opportunity_id)),...selectedChildren.map(r=>reserveFor(r.opportunity_id))];
const selection={version:'post-audit-source-selection-v2',clock,recommendation_results_used:false,quality_labels_observed:0,source_groups:selectedGroupIds.size,scopes:sample.map(s=>({...s,group_id:group(s.parent_id),title:(children.get(s.id)||parents.get(s.id)).title,family:meta.get(s.parent_id)?.family})),independent_child_scopes_available:childCandidates.length,independent_child_parent_groups:childGroups.length,selected_child_scopes:selectedChildren.length,limitations:['Existing source-group overlay retained; unknown successor relationships remain a limitation.','Only supported, previously unexposed native child projections are eligible. Siblings share one source-group denominator.','Difficult scientific families enter through source stratification, not recommendation quality. No guaranteed no-group cases are selected using output.'],excluded_groups:[...excludedGroups].sort(),rule:'Existing source-candidate metadata, current canonical non-broad parent records; deterministic SHA order within source-family round robin. Native independent children included first, at most six; total 24 parent groups. No replacement after labels.',prior_selection:'semantic-selection-v1.json preserved; before new outputs/labels, corrected an inherited parent-only synopsis heuristic that hid three existing native research children.'};
const selectionPath=DOC+'/semantic-selection-v2.json';if(fs.existsSync(selectionPath)&&JSON.stringify(read(selectionPath))!==JSON.stringify(selection))throw Error('Frozen source selection changed');
fs.mkdirSync(DOC,{recursive:true});fs.writeFileSync(selectionPath,JSON.stringify(selection,null,2)+'\n');
const cohorts={legacy:old,rollout50:original.cohort_50.map(reserveFor),rollout150:original.cohort_150.map(reserveFor),semantic:sample};
const packages={};
for(const [name,reservations]of Object.entries(cohorts)){
 const scopes=resolveSharedScopes(catalog,child,reservations),pack=await buildSharedPackage({catalog,sidecar:c.SUBTOPIC_CATALOG,directory:c.RESEARCHER_DIRECTORY,config:c.FACULTY_MATCHES,scopes});
 fs.writeFileSync(pack.path,pack.bytes);const indexPath=DOC+'/'+name+'-index.json';fs.writeFileSync(indexPath,JSON.stringify(pack.index,null,2)+'\n');packages[name]={requested:reservations.length,bound:scopes.length,parents:new Set(scopes.map(s=>s.parent_id)).size,children:scopes.filter(s=>s.record_type==='publishable_child').length,generation:pack.index.generation_id,index_path:indexPath,packet:pack.index.shared,missing:reservations.filter(r=>!scopes.some(s=>s.id===r.id)).map(r=>r.id),activated:false};
}
const ids=[...new Set([...old.map(r=>r.id),...original.cohort_150])];
const inventory=ids.map(id=>{const legacy=old.find(r=>r.id===id),r=children.get(id)||parents.get(id),parent=legacy?.parent_id||children.get(id)?.parent_id||id,canonical=Boolean(r&&(id===parent||r.parent_id===parent));return{id,parent_id:parent,legacy:!!legacy,previous_shared_105:read('docs/team-recommender/profile-repair/shared-candidate-index.json').scopes.some(s=>s.id===id),rollout50:original.cohort_50.includes(id),rollout150:original.cohort_150.includes(id),canonical,kind:children.has(id)?'publishable_child':'specific_parent',action_current:canonical&&c.FUNDING_RETRIEVAL.recordIsCurrent(r,new Date(clock))&&c.FUNDING_RETRIEVAL.recordIsCurrent(parents.get(parent),new Date(clock)),broad_unselected:canonical&&parents.has(id)&&!!prepared.get(id)?.isBroad,legacy_withheld:legacy?.review_state==='needs_revalidation',source_projection_missing:!canonical};});
fs.writeFileSync(DOC+'/routing-inventory-v1.json',JSON.stringify({clock,packages,rows:inventory,selection:selectionPath,substitutions:[],mapping_correction:{id:'eere-exchange:DE-TA1-0003589',before:'declared_branch',after:'specific_parent',basis:'Exact canonical catalog ID and self-parent; no title approximation. Unsupported 332894:superconducting-qubits has no native child projection.'}},null,2)+'\n');
fs.writeFileSync(OUT+'/semantic-canonical-sources.json',JSON.stringify(sample.map(s=>({scope:s,parent:parents.get(s.parent_id),record:children.get(s.id)||parents.get(s.id)})),null,2)+'\n');
console.log(JSON.stringify({packages,selection:{groups:selection.source_groups,scopes:sample.length,children:selectedChildren.length}},null,2));
