"""Durable accepted scope baseline and separate maintenance/backfill queues."""
import argparse
import ast
import inspect
import json
from pathlib import Path

from tools.offline_ai import atomic_json, config, identity


def science_contract():
    from scripts import build_opportunity_teams as t
    functions = [t.clean, t.validate_roles, t.validate_response, t.validate_edges]
    return identity([t.VERSION, t.RESPONSE_VERSION, t.DECOMPOSE, t.ADJUDICATE, t.VERIFY,
                     [ast.dump(ast.parse(inspect.getsource(fn)), include_attributes=False) for fn in functions]])


def snapshot(candidates, claims):
    return {'version': 1, 'scopes': {s['id']: s['source_fingerprint'] for s in candidates},
            'claims': {k: identity({n: c[n] for n in ('revision', 'material_hash', 'researcher_id')}) for k, c in claims.items()}}


def decision_key(scope, attempt, claims, scientific_identity=None):
    state = attempt.get('state') if isinstance(attempt, dict) else None
    dependencies = None
    if state not in ('not_specific', 'unsuitable_scope', 'provider_refusal'):
        names = attempt.get('claim_dependencies', list(claims)) if isinstance(attempt, dict) else list(claims)
        dependencies = {key: claims.get(key) for key in names}
        if state == 'insufficient_evidence':
            dependencies['@inventory'] = identity(sorted(claims))
    return identity([scientific_identity or science_contract(), scope['source_fingerprint'], dependencies])


def migrate_legacy(model, candidates, claims_generation, claims):
    """Annotate only hash-proven compatibility, preserving original provenance."""
    from scripts import build_opportunity_teams as t
    scientific_identity = science_contract()
    allowed = {entry['pipeline_hash'] for entry in config().get('legacy_team_contracts', [])
               if entry['science_contract'] == scientific_identity}
    invalidated = []
    for row in model['opportunities']:
        if not row.get('generator_version'):
            continue
        if row.get('decision_contract') == scientific_identity or row.get('pipeline_hash') in allowed:
            # Keep its original model/pipeline attribution. This is compatibility
            # evidence, not a claim it was generated by the new default route.
            row.setdefault('decision_contract', scientific_identity)
        else:
            row['review_state'] = 'needs_revalidation'
            row['revalidation_reason'] = 'The retained scientific decision contract cannot be established.'
            invalidated.append(row['id'])
    attempts = model.setdefault('generation_attempts', {})
    for scope in candidates:
        attempt = attempts.get(scope['id'])
        if not isinstance(attempt, dict) or attempt.get('decision_contract'):
            continue
        for pipeline in allowed:
            legacy_key = t.content_hash([pipeline, scope['source_fingerprint'], claims_generation,
                      t.ASSEMBLY_VERSION if attempt.get('state') == 'insufficient_evidence' else None])
            if attempt.get('key') == legacy_key and attempt.get('response_contract') == t.RESPONSE_VERSION:
                attempt['legacy_provenance'] = {'key': legacy_key, 'pipeline_hash': pipeline}
                attempt['decision_contract'] = scientific_identity
                attempt['key'] = decision_key(scope, attempt, claims, scientific_identity)
                break
    return invalidated


def queues(pending, existing, attempts, previous, current):
    maintenance, backfill, reasons = [], [], {}
    for scope in pending:
        key = scope['id']
        prior = previous['scopes'].get(key)
        attempt = attempts.get(key)
        reason = ('stale_published_team' if key in existing and existing[key].get('review_state') == 'needs_revalidation' else
                  'new_since_accepted_snapshot' if prior is None else
                  'source_changed' if prior != scope['source_fingerprint'] else
                  'decision_inputs_changed' if isinstance(attempt, dict) and attempt.get('state') in ('insufficient_evidence', 'proposed') else
                  'retryable_maintenance_failure' if isinstance(attempt, dict) and attempt.get('mode') in ('maintenance', 'pilot') else None)
        (maintenance if reason else backfill).append(scope)
        reasons[key] = reason or 'historical_unassessed_backfill'
    return maintenance, backfill, reasons


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--snapshot-before', type=Path)
    parser.add_argument('--rebuild-projections', action='store_true')
    args = parser.parse_args()
    from scripts import build_opportunity_teams as t
    if args.rebuild_projections:
        from scripts.researcher_registry import build_outputs
        from scripts.faculty_match import update_version_target
        build_outputs(Path('config/researcher_registry.json'), version_targets=[Path('team_match.html'), Path('match_explorer.html')])
        update_version_target(Path('team_match.html'), Path('data/faculty_matches.js'))
        return
    if not args.snapshot_before:
        parser.error('Select snapshot-before or rebuild-projections')
    registry = t.load_registry()
    model = json.loads(Path('config/opportunity_team_model.json').read_bytes())
    baseline = model.get('accepted_scope_snapshot') or snapshot(t.scopes(), t.eligible_claims(registry))
    atomic_json(args.snapshot_before, baseline)


if __name__ == '__main__':
    main()
