"""Durable accepted scope baseline and separate maintenance/backfill queues."""
import argparse
import ast
import inspect
import json
import copy
from pathlib import Path

from tools.offline_ai import atomic_json, config, identity


def science_contract():
    from scripts import build_opportunity_teams as t
    functions = [t.clean, t.validate_roles, t.validate_response, t.validate_edges]
    return identity([t.VERSION, t.RESPONSE_VERSION, t.DECOMPOSE, t.ADJUDICATE, t.VERIFY,
                     [ast.dump(ast.parse(inspect.getsource(fn)), include_attributes=False) for fn in functions]])


def snapshot(candidates, claims):
    return {'version': 1, 'scopes': {s['id']: s['source_fingerprint'] for s in candidates},
            'claims': {k: identity({n: c[n] for n in ('revision', 'material_hash', 'researcher_id')}) for k, c in claims.items()}}


def decision_key(scope, attempt, claims, scientific_identity=None):
    state = attempt.get('state') if isinstance(attempt, dict) else None
    dependencies = None
    if state not in ('not_specific', 'unsuitable_scope', 'provider_refusal'):
        names = attempt.get('claim_dependencies', list(claims)) if isinstance(attempt, dict) else list(claims)
        dependencies = {key: claims.get(key) for key in names}
        if state == 'insufficient_evidence':
            dependencies['@inventory'] = identity(sorted(claims))
    return identity([scientific_identity or science_contract(), scope['source_fingerprint'], dependencies])


def migrate_legacy(model, candidates, claims_generation, claims):
    """Annotate only hash-proven compatibility, preserving original provenance."""
    from scripts import build_opportunity_teams as t
    scientific_identity = science_contract()
    allowed = {entry['pipeline_hash'] for entry in config().get('legacy_team_contracts', [])
               if entry['science_contract'] == scientific_identity}
    invalidated = []
    for row in model['opportunities']:
        if not row.get('generator_version'):
            continue
        if row.get('decision_contract') == scientific_identity or row.get('pipeline_hash') in allowed:
            # Keep its original model/pipeline attribution. This is compatibility
            # evidence, not a claim it was generated by the new default route.
            row.setdefault('decision_contract', scientific_identity)
        else:
            row['review_state'] = 'needs_revalidation'
            row['revalidation_reason'] = 'The retained scientific decision contract cannot be established.'
            invalidated.append(row['id'])
    attempts = model.setdefault('generation_attempts', {})
    for scope in candidates:
        attempt = attempts.get(scope['id'])
        if not isinstance(attempt, dict) or attempt.get('decision_contract'):
            continue
        for pipeline in allowed:
            legacy_key = t.content_hash([pipeline, scope['source_fingerprint'], claims_generation,
                      t.ASSEMBLY_VERSION if attempt.get('state') == 'insufficient_evidence' else None])
            if attempt.get('key') == legacy_key and attempt.get('response_contract') == t.RESPONSE_VERSION:
                attempt['legacy_provenance'] = {'key': legacy_key, 'pipeline_hash': pipeline}
                attempt['decision_contract'] = scientific_identity
                attempt['key'] = decision_key(scope, attempt, claims, scientific_identity)
                break
    return invalidated


def retained_decision_hash(row):
    from scripts.build_opportunity_teams import content_hash
    return content_hash({key: row.get(key) for key in (
        'id', 'parent_id', 'record_type', 'source_fingerprint', 'pipeline_hash',
        'generator_version', 'objective', 'roles', 'members', 'variants', 'missing_skills')})


def curated_profile_hashes(row, registry):
    from scripts.researcher_registry import legacy_faculty_projection
    profiles = {profile['id']: profile for profile in legacy_faculty_projection(registry)}
    references = {member['faculty_id'] for member in row['members']}
    for role in row['roles']:
        references.update(role.get('candidate_ids', []))
        references.update(role.get('alternative_ids', []))
    return {identifier: identity(profiles[identifier]) for identifier in sorted(references)}


def restore_proven_teams(model, candidates, registry):
    """Restore only exact previously published decisions with current evidence proofs."""
    from scripts import build_opportunity_teams as t
    from scripts.researcher_registry import validate_opportunity_team_dependencies
    proof = config().get('targeted_team_recovery')
    if not proof:
        return []
    scientific = science_contract()
    scopes, claims = {row['id']: row for row in candidates}, t.eligible_claims(registry)
    current_sources = t.source_fingerprints(model, candidates)
    results = []
    for row in model['opportunities']:
        if row['id'] not in proof['published_decisions'] or row.get('review_state') != 'needs_revalidation':
            continue
        result = {'scope_id': row['id'], 'state': 'pending', 'provider_requests': 0}
        results.append(result)
        scope = scopes.get(row['id'])
        source_review = proof.get('reviewed_source_changes', {}).get(row['id'])
        curated = bool(source_review and source_review.get('review_kind') == 'curated_source_revalidation'
                       and not row.get('generator_version'))
        fingerprint = current_sources.get(row['id']) if curated else (scope or {}).get('source_fingerprint')
        reviewed_change = bool(scope and source_review
            and source_review.get('prior_source_fingerprint') == row.get('source_fingerprint')
            and source_review.get('reviewed_source_fingerprint') == fingerprint)
        if not scope or (row.get('source_fingerprint') != fingerprint and not reviewed_change):
            result['reason'] = ('source_changed' if scope else
                'declared_scope_requires_source_revalidation' if row['id'] in current_sources else 'source_ineligible')
            continue
        if (proof['scientific_contract'] != scientific
                or (not curated and row.get('pipeline_hash') not in proof['compatible_pipeline_hashes'])
                or retained_decision_hash(row) != proof['published_decisions'][row['id']]):
            result['reason'] = 'retained_decision_provenance_unestablished'
            continue
        try:
            # The dependency validator intentionally skips withheld rows. Check
            # an active copy; only the successful complete proof can clear flags.
            inspected = copy.deepcopy(row)
            inspected['review_state'] = 'proposed'
            validate_opportunity_team_dependencies(registry,
                {'faculty': model['faculty'], 'opportunities': [inspected]})
            if curated:
                quotes = source_review.get('role_source_quotes', {})
                if (not reviewed_change or row['record_type'] != source_review.get('record_type')
                        or curated_profile_hashes(row, registry) != source_review.get('reviewed_profile_hashes')
                        or set(quotes) != {role['id'] for role in row['roles']}
                        or any(not isinstance(quote, str) or not 15 <= len(quote) <= 400
                               or quote not in scope['text'] for quote in quotes.values())
                        or len({member['faculty_id'] for member in row['members']}) < 2):
                    raise ValueError('Curated source/profile proof mismatch')
                proposal = {'source_fingerprint': fingerprint}
            else:
                proposal = restored_generated_proposal(row, scope, claims)
            if not proposal:
                result['reason'] = 'no_complementary_team'
                continue
        except (ValueError, KeyError, TypeError):
            result['reason'] = 'current_evidence_contract_failed'
            continue
        row.update(proposal)
        if curated:
            row.pop('review_state', None)  # Restore the original curated representation.
        else:
            row['decision_contract'] = scientific
        row['recovery_proof'] = {'version': proof['version'], 'published_sha': proof['published_sha'],
            'retained_decision_hash': proof['published_decisions'][row['id']],
            'registry_generation': registry['registry_generation'],
            'source_fingerprint': fingerprint, 'provider_requests': 0}
        if curated:
            row['recovery_proof']['validation_contract'] = 'curated-source-and-profile-1'
        else:
            row['recovery_proof']['scientific_contract'] = scientific
        if reviewed_change:
            row['recovery_proof']['source_revalidation'] = source_review
        row.pop('revalidation_reason', None)
        result.update(state='restored_from_retained_evidence', proof=row['recovery_proof'])
    return results


def restored_generated_proposal(row, scope, claims):
    from scripts import build_opportunity_teams as t
    # Generated decisions continue through their exact original assembly gate;
    # explicit legacy curated reviews never make this gate optional for them.
    decomposition = {'specific': True, 'objective': row['objective'], 'roles': [
        {'id': role['id'], 'label': role['label'], 'required': role['required'],
         'quote': role['source_quote']} for role in row['roles']]}
    edges = [{'role_id': role['id'], 'claim_id': ref['claim_id'],
              'coverage': ref['coverage'], 'reason': ref['reason']}
             for role in row['roles'] for ref in role['claim_refs']]
    return t.assemble(scope, decomposition, edges, claims, row['registry_generation_at_generation'])


def load_queue_report(path):
    """A partial diagnostic write cannot block recovery from the durable model."""
    try:
        report = json.loads(Path(path).read_bytes())
    except (OSError, ValueError, UnicodeError):
        return {}
    return report if isinstance(report, dict) else {}


def retained_queue_reasons(report, input_generation, response_contract):
    """Recover queue provenance from the exact completed generation's safe report."""
    if (report.get('status') != 'completed' or report.get('generation_requested') is not True
            or report.get('mode') not in ('maintenance', 'pilot')
            or report.get('input_generation') != input_generation
            or report.get('response_contract') != response_contract
            or not isinstance(report.get('queue_reasons'), dict)):
        return {}
    reasons = {'stale_published_team', 'new_since_accepted_snapshot', 'source_changed',
               'decision_inputs_changed', 'retryable_maintenance_failure'}
    return {key: value for key, value in report.get('queue_reasons', {}).items() if value in reasons}


def preserve_deferred(attempts, selected, results, reasons, mode, scientific_identity, attempt_key):
    """Keep maintenance ownership without rewriting a prior failed assessment."""
    processed = {row['scope_id'] for row in results if row['state'] != 'deferred'}
    for scope in selected:
        key = scope['id']
        if key in processed:
            continue
        previous = attempts.get(key)
        from scripts.build_opportunity_teams import COMPLETED_STATES
        if not isinstance(previous, dict) or previous.get('state') in COMPLETED_STATES:
            attempts[key] = {'state': 'deferred', 'mode': mode, 'decision_contract': scientific_identity,
                'stage': 'queue', 'reason': reasons[key], 'next_action': 'retry_maintenance', 'retry_after': 0}
            attempts[key]['key'] = attempt_key(scope)
        else:
            previous['maintenance_pending'] = {'reason': reasons[key], 'next_action':
                'human_provider_configuration' if previous.get('state') == 'provider_refusal' else 'retry_maintenance'}


def queues(pending, existing, attempts, previous, current, retained_reasons=None):
    maintenance, backfill, reasons = [], [], {}
    for scope in pending:
        key = scope['id']
        prior = previous['scopes'].get(key)
        attempt = attempts.get(key)
        reason = ('stale_published_team' if key in existing and existing[key].get('review_state') == 'needs_revalidation' else
                  'new_since_accepted_snapshot' if prior is None else
                  'source_changed' if prior != scope['source_fingerprint'] else
                  'decision_inputs_changed' if isinstance(attempt, dict) and attempt.get('state') in ('insufficient_evidence', 'proposed') else
                  'retryable_maintenance_failure' if isinstance(attempt, dict) and
                      (attempt.get('mode') in ('maintenance', 'pilot') or attempt.get('maintenance_pending')
                       or key in (retained_reasons or {})) else None)
        (maintenance if reason else backfill).append(scope)
        reasons[key] = reason or 'historical_unassessed_backfill'
    return maintenance, backfill, reasons


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--snapshot-before', type=Path)
    parser.add_argument('--rebuild-projections', action='store_true')
    args = parser.parse_args()
    from scripts import build_opportunity_teams as t
    if args.rebuild_projections:
        from scripts.researcher_registry import build_outputs
        from scripts.faculty_match import update_version_target
        build_outputs(Path('config/researcher_registry.json'), version_targets=[Path('team_match.html'), Path('match_explorer.html')])
        update_version_target(Path('team_match.html'), Path('data/faculty_matches.js'))
        return
    if not args.snapshot_before:
        parser.error('Select snapshot-before or rebuild-projections')
    registry = t.load_registry()
    model = json.loads(Path('config/opportunity_team_model.json').read_bytes())
    baseline = model.get('accepted_scope_snapshot') or snapshot(t.scopes(), t.eligible_claims(registry))
    atomic_json(args.snapshot_before, baseline)


if __name__ == '__main__':
    main()
