"""Durable accepted scope baseline and separate maintenance/backfill queues."""
import argparse
import ast
import inspect
import json
import copy
from pathlib import Path

from tools.offline_ai import atomic_json, config, identity


def science_contract():
    from scripts import build_opportunity_teams as t
    from tools.team_provider import stage_prompt, request_inputs
    functions = [t.clean, t.validate_roles, t.validate_response, t.validate_edges, request_inputs]
    return identity([t.VERSION, t.RESPONSE_VERSION, *[stage_prompt(stage) for stage in ('decomposition', 'adjudication', 'verification')],
                     [ast.dump(ast.parse(inspect.getsource(fn)), include_attributes=False) for fn in functions]])


def compatible_contracts(state=None):
    active = science_contract()
    return {active} | {row['retained'] for row in config().get('team_decision_compatibility', [])
                      if row['active'] == active and (state is None or state in row.get('states',
                          ['proposed', 'insufficient_evidence', 'not_specific', 'unsuitable_scope', 'provider_refusal']))}


def snapshot(candidates, claims):
    return {'version': 1, 'scopes': {s['id']: s['source_fingerprint'] for s in candidates},
            'claims': {k: identity({n: c[n] for n in ('revision', 'material_hash', 'researcher_id')}) for k, c in claims.items()}}


def decision_key(scope, attempt, claims, scientific_identity=None):
    state = attempt.get('state') if isinstance(attempt, dict) else None
    dependencies = None
    if state not in ('not_specific', 'unsuitable_scope', 'provider_refusal'):
        names = attempt.get('claim_dependencies', list(claims)) if isinstance(attempt, dict) else list(claims)
        dependencies = {key: claims.get(key) for key in names}
        if state == 'insufficient_evidence':
            dependencies['@inventory'] = identity(sorted(claims))
    if scientific_identity is None:
        retained = attempt.get('decision_contract') if isinstance(attempt, dict) else None
        scientific_identity = retained if retained in compatible_contracts(state) else science_contract()
    return identity([scientific_identity, scope['source_fingerprint'], dependencies])


def migrate_legacy(model, candidates, claims_generation, claims):
    """Annotate only hash-proven compatibility, preserving original provenance."""
    from scripts import build_opportunity_teams as t
    scientific_identity = science_contract()
    compatible = compatible_contracts()
    allowed = {entry['pipeline_hash']: entry['science_contract'] for entry in config().get('legacy_team_contracts', [])
               if entry['science_contract'] in compatible}
    invalidated = []
    for row in model['opportunities']:
        if not row.get('generator_version'):
            continue
        if row.get('decision_contract') in compatible or row.get('pipeline_hash') in allowed:
            # Keep its original model/pipeline attribution. This is compatibility
            # evidence, not a claim it was generated by the new default route.
            row.setdefault('decision_contract', allowed.get(row.get('pipeline_hash'), scientific_identity))
        else:
            row['review_state'] = 'needs_revalidation'
            row['revalidation_reason'] = 'The retained scientific decision contract cannot be established.'
            invalidated.append(row['id'])
    attempts = model.setdefault('generation_attempts', {})
    for scope in candidates:
        attempt = attempts.get(scope['id'])
        if not isinstance(attempt, dict) or attempt.get('decision_contract'):
            continue
        for pipeline in allowed:
            legacy_key = t.content_hash([pipeline, scope['source_fingerprint'], claims_generation,
                      t.ASSEMBLY_VERSION if attempt.get('state') == 'insufficient_evidence' else None])
            if attempt.get('key') == legacy_key and attempt.get('response_contract') == t.RESPONSE_VERSION:
                attempt['legacy_provenance'] = {'key': legacy_key, 'pipeline_hash': pipeline}
                attempt['decision_contract'] = allowed[pipeline]
                attempt['key'] = decision_key(scope, attempt, claims, allowed[pipeline])
                break
    return invalidated


def retained_decision_hash(row):
    from scripts.build_opportunity_teams import content_hash
    return content_hash({key: row.get(key) for key in (
        'id', 'parent_id', 'record_type', 'source_fingerprint', 'pipeline_hash',
        'generator_version', 'objective', 'roles', 'members', 'variants', 'missing_skills')})


def curated_profile_hashes(row, registry):
    from scripts.researcher_registry import legacy_faculty_projection
    profiles = {profile['id']: profile for profile in legacy_faculty_projection(registry)}
    references = {member['faculty_id'] for member in row['members']}
    for role in row['roles']:
        references.update(role.get('candidate_ids', []))
        references.update(role.get('alternative_ids', []))
    return {identifier: identity(profiles[identifier]) for identifier in sorted(references)}


def restore_proven_teams(model, candidates, registry):
    """Restore only exact previously published decisions with current evidence proofs."""
    from scripts import build_opportunity_teams as t
    from scripts.researcher_registry import validate_opportunity_team_dependencies
    proof = config().get('targeted_team_recovery')
    if not proof:
        return []
    scientific = proof['scientific_contract']
    scopes, claims = {row['id']: row for row in candidates}, t.eligible_claims(registry)
    current_sources = t.source_fingerprints(model, candidates)
    results = []
    for row in model['opportunities']:
        if row['id'] not in proof['published_decisions'] or row.get('review_state') != 'needs_revalidation':
            continue
        result = {'scope_id': row['id'], 'state': 'pending', 'provider_requests': 0}
        results.append(result)
        scope = scopes.get(row['id'])
        source_review = proof.get('reviewed_source_changes', {}).get(row['id'])
        curated = bool(source_review and source_review.get('review_kind') == 'curated_source_revalidation'
                       and not row.get('generator_version'))
        fingerprint = current_sources.get(row['id']) if curated else (scope or {}).get('source_fingerprint')
        reviewed_change = bool(scope and source_review
            and source_review.get('prior_source_fingerprint') == row.get('source_fingerprint')
            and source_review.get('reviewed_source_fingerprint') == fingerprint)
        if not scope or (row.get('source_fingerprint') != fingerprint and not reviewed_change):
            result['reason'] = ('source_changed' if scope else
                'declared_scope_requires_source_revalidation' if row['id'] in current_sources else 'source_ineligible')
            continue
        if (scientific not in compatible_contracts()
                or (not curated and row.get('pipeline_hash') not in proof['compatible_pipeline_hashes'])
                or retained_decision_hash(row) != proof['published_decisions'][row['id']]):
            result['reason'] = 'retained_decision_provenance_unestablished'
            continue
        try:
            # The dependency validator intentionally skips withheld rows. Check
            # an active copy; only the successful complete proof can clear flags.
            inspected = copy.deepcopy(row)
            inspected['review_state'] = 'proposed'
            validate_opportunity_team_dependencies(registry,
                {'faculty': model['faculty'], 'opportunities': [inspected]})
            if curated:
                quotes = source_review.get('role_source_quotes', {})
                if (not reviewed_change or row['record_type'] != source_review.get('record_type')
                        or curated_profile_hashes(row, registry) != source_review.get('reviewed_profile_hashes')
                        or set(quotes) != {role['id'] for role in row['roles']}
                        or any(not isinstance(quote, str) or not 15 <= len(quote) <= 400
                               or quote not in scope['text'] for quote in quotes.values())
                        or len({member['faculty_id'] for member in row['members']}) < 2):
                    raise ValueError('Curated source/profile proof mismatch')
                proposal = {'source_fingerprint': fingerprint}
            else:
                updates = (source_review or {}).get('role_quote_updates')
                inspected = copy.deepcopy(row)
                if updates is not None:
                    if (not reviewed_change or source_review.get('review_kind') != 'source_quote_revalidation'
                            or not isinstance(updates, dict) or not updates
                            or not set(updates).issubset({role['id'] for role in inspected['roles']})):
                        raise ValueError('Explicit source quote review required')
                    for role in inspected['roles']:
                        if role['id'] not in updates:
                            continue
                        change = updates[role['id']]
                        if (change['before'] != role['source_quote'] or change['before'] in scope['text']
                                or not isinstance(change['after'], str) or change['after'] not in scope['text']):
                            raise ValueError('Reviewed old/current source quote mismatch')
                        role['source_quote'] = change['after']
                proposal = restored_generated_proposal(inspected, scope, claims)
                if updates is not None and (not proposal or retained_decision_hash(dict(row, **proposal))
                        != source_review.get('reviewed_decision_hash')):
                    raise ValueError('Reviewed team decision changed during citation reprojection')
            if not proposal:
                result['reason'] = 'no_complementary_team'
                continue
        except (ValueError, KeyError, TypeError):
            result['reason'] = 'current_evidence_contract_failed'
            continue
        row.update(proposal)
        if curated:
            row.pop('review_state', None)  # Restore the original curated representation.
        else:
            row['decision_contract'] = scientific
        row['recovery_proof'] = {'version': proof['version'], 'published_sha': proof['published_sha'],
            'retained_decision_hash': proof['published_decisions'][row['id']],
            'registry_generation': registry['registry_generation'],
            'source_fingerprint': fingerprint, 'provider_requests': 0}
        if curated:
            row['recovery_proof']['validation_contract'] = 'curated-source-and-profile-1'
        else:
            row['recovery_proof']['scientific_contract'] = scientific
        if reviewed_change:
            row['recovery_proof']['source_revalidation'] = source_review
        row.pop('revalidation_reason', None)
        result.update(state='restored_from_retained_evidence', proof=row['recovery_proof'])
    retirements = restore_after_claim_retirement(model, candidates, registry, proof)
    return list({row['scope_id']: row for row in [*results, *retirements]}.values())


def restore_after_claim_retirement(model, candidates, registry, recovery):
    """Reassemble reviewed published graphs after removing explicitly retired evidence."""
    from scripts import build_opportunity_teams as t
    from scripts.researcher_registry import validate_opportunity_team_dependencies
    proof = recovery.get('claim_retirement_recovery', {})
    scopes = {scope['id']: scope for scope in candidates}
    claims = t.eligible_claims(registry)
    inventory = {claim['claim_id']: (person['researcher_id'], claim)
                 for person in registry['researchers'] for claim in person['claims']}
    scientific = recovery['scientific_contract']
    results = []
    for row in model['opportunities']:
        reviewed = proof.get('decisions', {}).get(row['id'])
        if not reviewed or row.get('review_state') != 'needs_revalidation':
            continue
        result = {'scope_id': row['id'], 'state': 'pending', 'provider_requests': 0,
                  'reason': 'claim_retirement_proof_mismatch'}
        results.append(result)
        try:
            scope = scopes[row['id']]
            if (proof['registry_generation'] != registry['registry_generation']
                    or scientific not in compatible_contracts()
                    or row.get('decision_contract') != scientific
                    or row.get('pipeline_hash') not in recovery['compatible_pipeline_hashes']
                    or not row.get('generator_version')
                    or reviewed['retained_decision_hash'] != retained_decision_hash(row)
                    or row['source_fingerprint'] != scope['source_fingerprint']
                    or reviewed['source_fingerprint'] != scope['source_fingerprint']):
                raise ValueError('Retained source/decision identity changed')
            removed = set(reviewed['removed_claim_ids'])
            seen_removed = set()
            inspected = copy.deepcopy(row)
            for role in inspected['roles']:
                kept = []
                for ref in role['claim_refs']:
                    key = ref['claim_id']
                    if key in removed:
                        person, claim = inventory[key]
                        if claim['status'] != 'retired' or person != ref['researcher_id']:
                            raise ValueError('Only explicit claim retirement can remove an edge')
                        seen_removed.add(key)
                    else:
                        if any(ref[name] != claims[key][name] for name in
                               ('claim_id', 'revision', 'material_hash', 'researcher_id')):
                            raise ValueError('Remaining claim evidence changed')
                        kept.append(ref)
                role['claim_refs'] = kept
            if not removed or seen_removed != removed:
                raise ValueError('Retirement review does not match the retained graph')
            proposal = restored_generated_proposal(inspected, scope, claims)
            if not proposal:
                if reviewed['reassembled_decision_hash'] is not None:
                    raise ValueError('Reviewed complementary team is no longer reproducible')
                result.update(state='withheld_after_claim_retirement', reason='no_complementary_team')
                continue
            assembled = dict(row, **proposal)
            if retained_decision_hash(assembled) != reviewed['reassembled_decision_hash']:
                raise ValueError('Reassembly differs from the explicitly reviewed decision')
            validate_opportunity_team_dependencies(registry,
                {'faculty': model['faculty'], 'opportunities': [assembled]})
        except (ValueError, KeyError, TypeError):
            continue
        row.update(proposal)
        row.pop('revalidation_reason', None)
        row['claim_retirement_proof'] = {'version': 1, 'published_sha': proof['published_sha'],
            'registry_generation': registry['registry_generation'], 'scientific_contract': scientific,
            **reviewed, 'provider_requests': 0}
        result.update(state='restored_from_retained_evidence', reason='retired_claim_edges_removed',
                      proof=row['claim_retirement_proof'])
    return results


def restored_generated_proposal(row, scope, claims):
    from scripts import build_opportunity_teams as t
    # Generated decisions continue through their exact original assembly gate;
    # explicit legacy curated reviews never make this gate optional for them.
    decomposition = {'specific': True, 'objective': row['objective'], 'roles': [
        {'id': role['id'], 'label': role['label'], 'required': role['required'],
         'quote': role['source_quote']} for role in row['roles']]}
    edges = [{'role_id': role['id'], 'claim_id': ref['claim_id'],
              'coverage': ref['coverage'], 'reason': ref['reason']}
             for role in row['roles'] for ref in role['claim_refs']]
    return t.assemble(scope, decomposition, edges, claims, row['registry_generation_at_generation'])


def reassemble_changed_claims(model, candidates, registry):
    """Prune stale evidence from an otherwise unchanged verified team graph."""
    from scripts import build_opportunity_teams as t
    from scripts.researcher_registry import validate_opportunity_team_dependencies
    scopes, claims = {scope['id']: scope for scope in candidates}, t.eligible_claims(registry)
    compatible = compatible_contracts()
    results = []
    for row in model['opportunities']:
        scope = scopes.get(row['id'])
        if (row.get('review_state') != 'needs_revalidation' or not row.get('generator_version')
                or row.get('decision_contract') not in compatible or not scope
                or row.get('source_fingerprint') != scope['source_fingerprint']):
            continue
        inspected, removed = copy.deepcopy(row), []
        try:
            for role in inspected['roles']:
                kept = []
                for ref in role['claim_refs']:
                    claim = claims.get(ref['claim_id'])
                    if claim and all(ref[name] == claim[name] for name in ('claim_id', 'revision', 'material_hash', 'researcher_id')):
                        kept.append(ref)
                    else:
                        removed.append({name: ref[name] for name in ('claim_id', 'revision', 'material_hash', 'researcher_id')})
                role['claim_refs'] = kept
            if not removed:
                continue
            proposal = restored_generated_proposal(inspected, scope, claims)
            if not proposal:
                results.append({'scope_id': row['id'], 'state': 'needs_reassessment',
                                'reason': 'remaining_graph_has_no_complementary_team', 'provider_requests': 0})
                continue
            assembled = row | proposal
            validate_opportunity_team_dependencies(registry, {'faculty': model['faculty'], 'opportunities': [assembled]})
        except (ValueError, KeyError, TypeError):
            continue  # Withheld evidence never becomes publishable on a partial proof.
        proof = {'version': 'current-claim-reassembly-1', 'prior_decision_hash': retained_decision_hash(row),
            'retained_scientific_contract': row['decision_contract'], 'source_fingerprint': scope['source_fingerprint'],
            'current_registry_generation': registry['registry_generation'], 'removed_references': removed,
            'reassembled_decision_hash': retained_decision_hash(assembled), 'provider_requests': 0}
        row.update(proposal)
        row.pop('revalidation_reason', None)
        row['claim_update_proof'] = proof
        results.append({'scope_id': row['id'], 'state': 'reassembled_from_current_evidence', 'proof': proof})
    return results


def load_queue_report(path):
    """A partial diagnostic write cannot block recovery from the durable model."""
    try:
        report = json.loads(Path(path).read_bytes())
    except (OSError, ValueError, UnicodeError):
        return {}
    return report if isinstance(report, dict) else {}


def retained_queue_reasons(report, input_generation, response_contract):
    """Recover queue provenance from the exact completed generation's safe report."""
    if (report.get('status') != 'completed' or report.get('generation_requested') is not True
            or report.get('mode') not in ('maintenance', 'pilot')
            or report.get('input_generation') != input_generation
            or report.get('response_contract') != response_contract
            or not isinstance(report.get('queue_reasons'), dict)):
        return {}
    reasons = {'stale_published_team', 'new_since_accepted_snapshot', 'source_changed',
               'decision_inputs_changed', 'retryable_maintenance_failure'}
    return {key: value for key, value in report.get('queue_reasons', {}).items() if value in reasons}


def preserve_deferred(attempts, selected, results, reasons, mode, scientific_identity, attempt_key):
    """Keep maintenance ownership without rewriting a prior failed assessment."""
    processed = {row['scope_id'] for row in results if row['state'] != 'deferred'}
    for scope in selected:
        key = scope['id']
        if key in processed:
            continue
        previous = attempts.get(key)
        from scripts.build_opportunity_teams import COMPLETED_STATES
        if not isinstance(previous, dict) or previous.get('state') in COMPLETED_STATES:
            attempts[key] = {'state': 'deferred', 'mode': mode, 'decision_contract': scientific_identity,
                'stage': 'queue', 'reason': reasons[key], 'next_action': 'retry_maintenance', 'retry_after': 0}
            attempts[key]['key'] = attempt_key(scope)
        else:
            previous['maintenance_pending'] = {'reason': reasons[key], 'next_action':
                'human_provider_configuration' if previous.get('state') == 'provider_refusal' else 'retry_maintenance'}


def queues(pending, existing, attempts, previous, current, retained_reasons=None):
    maintenance, backfill, reasons = [], [], {}
    for scope in pending:
        key = scope['id']
        prior = previous['scopes'].get(key)
        attempt = attempts.get(key)
        reason = ('stale_published_team' if key in existing and existing[key].get('review_state') == 'needs_revalidation' else
                  'new_since_accepted_snapshot' if prior is None else
                  'source_changed' if prior != scope['source_fingerprint'] else
                  'decision_inputs_changed' if isinstance(attempt, dict) and attempt.get('state') in ('insufficient_evidence', 'proposed') else
                  'retryable_maintenance_failure' if isinstance(attempt, dict) and
                      (attempt.get('mode') in ('maintenance', 'pilot') or attempt.get('maintenance_pending')
                       or key in (retained_reasons or {})) else None)
        (maintenance if reason else backfill).append(scope)
        reasons[key] = reason or 'historical_unassessed_backfill'
    return maintenance, backfill, reasons


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--snapshot-before', type=Path)
    parser.add_argument('--rebuild-projections', action='store_true')
    args = parser.parse_args()
    from scripts import build_opportunity_teams as t
    if args.rebuild_projections:
        from scripts.researcher_registry import build_outputs
        from scripts.faculty_match import update_version_target
        build_outputs(Path('config/researcher_registry.json'), version_targets=[Path('team_match.html'), Path('match_explorer.html')])
        update_version_target(Path('team_match.html'), Path('data/faculty_matches.js'))
        return
    if not args.snapshot_before:
        parser.error('Select snapshot-before or rebuild-projections')
    registry = t.load_registry()
    model = json.loads(Path('config/opportunity_team_model.json').read_bytes())
    baseline = model.get('accepted_scope_snapshot') or snapshot(t.scopes(), t.eligible_claims(registry))
    atomic_json(args.snapshot_before, baseline)


if __name__ == '__main__':
    main()
