import fs from 'node:fs';import os from 'node:os';import assert from 'node:assert/strict';import {chromium} from '@playwright/test';
const root='outputs/team-recommender-stage3',read=p=>JSON.parse(fs.readFileSync(p)),browser=await chromium.launch({headless:true}),observations=[];
for(const cohort of ['rollout50','rollout150']){
 const context=await browser.newContext({extraHTTPHeaders:{'x-stage3-cohort':cohort}}),page=await context.newPage(),requests=[];let phase='startup';
 page.on('request',r=>requests.push({url:r.url(),method:r.method(),phase}));await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await page.goto('http://127.0.0.1:8767/match_explorer.html?gate4-e2e=1');await page.waitForFunction(()=>globalThis.OpportunityTeam&&globalThis.RESEARCHER_DIRECTORY);
 assert(!requests.some(r=>/data\/team-recommender\/|assets\/team-(recommender|ingredients)/.test(r.url)));
 const cdp=await context.newCDPSession(page);await cdp.send('HeapProfiler.collectGarbage');const before=await cdp.send('Runtime.getHeapUsage');
 await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:20e6/8,uploadThroughput:20e6/8});
 phase='cold-input';const cold=await page.evaluate(async()=>{const t=performance.now();globalThis.validationData=await OpportunityTeam.loadData();globalThis.validationEngine=OpportunityTeam.create(validationData);return {ms:performance.now()-t,statistics:validationEngine.statistics(),resources:performance.getEntriesByType('resource').filter(r=>/team-recommender\/|team-(ingredients|recommender)\.js/.test(r.name)).map(r=>({name:r.name,duration:r.duration,encoded:r.encodedBodySize,decoded:r.decodedBodySize,transfer:r.transferSize}))};});
 await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
 assert.equal(cold.statistics.matrices,0);assert.equal(cold.statistics.optimizations,0);
 const bundle=read(root+'/assembled-'+cohort+'-v3/bundle.json'),ctx=read(root+'/assembled-'+cohort+'-v3/context.json');
 const ids=cohort==='holdout_effective'?bundle.scopes.filter(s=>s.prepared).map(s=>s.id):['359696'];
 phase='prepared-actions';const timings=await page.evaluate(({ids,ctx,bundle})=>{const e=validationEngine,rows=[];for(const id of ids){const scope=bundle.scopes.find(s=>s.id===id),input={scopeId:id,parentId:scope.parent_id,record:ctx.parents[scope.parent_id],childCatalog:{opportunities:Object.values(ctx.records).filter(r=>r.parent_id)},now:new Date()};let decision=e.resolveScope(input);if(!decision.ok){rows.push({id,blocked:decision.reason});continue;}const t=performance.now();let state=e.proposal(decision.opportunity),view=e.proposalView(state),opts=e.proposalOptions(state),built=performance.now();const repeats=[];for(let k=0;k<5;k++){const t=performance.now();e.resolveScope({...input,now:new Date()});e.proposal(decision.opportunity);e.proposalView(state);e.proposalOptions(state);repeats.push(performance.now()-t);}const edits=[];if(state.selectedIds.length){const first=state.selectedIds[0];for(let k=0;k<5;k++){e.resolveScope({...input,now:new Date()});const t=performance.now();state=e.removeMember(state,first);e.proposalOptions(state);state=e.addReplacement(state,first);e.proposalView(state);edits.push(performance.now()-t);}}rows.push({id,build_ms:built-t,cached_ms:repeats,edit_ms:edits,options:opts.length,selected:state.selectedIds.length,matched:view.selected.length+view.replacements.length,matched_expected:view.matched_people_count});}return {rows,statistics:e.statistics()};},{ids,ctx,bundle});
 for(const r of timings.rows)if(!r.blocked)assert.equal(r.matched,r.matched_expected);
 await cdp.send('HeapProfiler.collectGarbage');const after=await cdp.send('Runtime.getHeapUsage');
 const provider= requests.filter(r=>r.phase!=='startup'&&!r.url.startsWith('http://127.0.0.1:8767/'));assert.equal(provider.length,0);
 observations.push({cohort,cold,timings,heap_before:before,heap_after:after,extra_used_heap:after.usedSize-before.usedSize,requests,provider_requests:provider.length});await context.close();
}
// Reload the preserved valid routing on this local transport only.
const rollback=await browser.newContext(),p=await rollback.newPage();await p.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await p.goto('http://127.0.0.1:8767/match_explorer.html?gate4-e2e=1');await p.waitForFunction(()=>globalThis.OpportunityTeam&&globalThis.RESEARCHER_DIRECTORY);const restored=await p.evaluate(async()=>{const index=OpportunityTeam.availabilityIndex(),data=await OpportunityTeam.loadData();return {generation:index.generation_id,schema:index.schema_version,scope_count:data.scope_count,loaded:true};});assert.equal(restored.schema,1);
const result={version:'S3-real-Chromium-resource-observations-v2',browser:await browser.version(),node:process.version,os:os.release(),cpu:os.cpus()[0].model,logical_cpus:os.cpus().length,memory_bytes:os.totalmem(),network:'Real local gzip HTTP, Chromium CDP 20 Mbps/150 ms network emulation during cold input; no CPU throttle; not physical mobile',cold_observations_per_package:1,observations,rollback:restored,production_flip:false,physical_device:'NOT RUN'};
await browser.close();fs.writeFileSync('docs/team-recommender/receipts/stage3-browser-resources-v2.json',JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify(observations.map(o=>({cohort:o.cohort,cold_ms:o.cold.ms,extra_heap:o.extra_used_heap,builds:o.timings.rows.filter(r=>!r.blocked).length,provider_requests:o.provider_requests})))+'\nrollback '+JSON.stringify(restored));
